
export const menuData = [
// {
// title:"Category",
// items:[
// {name: "Plants", date: null },
// {name: "Flowers", date: null },
// {name: "Cakes", date: null },
// {name: "Gifts", date: null },
// {name: "Hampers", date: null },
// {name: "Chocolate Gifts", date: null },
// {name: "Combos", date: null },
// ]
// },
{
title: "Flowers",
items: [
{category:'SubCategoryFilters', name: "Roses", date: null },
{ category: 'SubCategoryFilters', name: "Lilies", date: null },
{ category: 'SubCategoryFilters', name: "Orchids", date: null },
{ category: 'SubCategoryFilters', name: "Mixed", date: null },
{ category: 'SubCategoryFilters', name: "Carnation", date: null },
{ category: 'SubCategoryFilters', name: "Gerbera", date: null },
{ category: "festival", name: "Christmas", date: null },
  { category: "festival", name: "Lohri", date: null },
  { category: "festival", name: "Holi", date: null },
  { category: "festival", name: "Eid Al Fitr", date: null },
  { category: "festival", name: "Rakhi", date: null },

  // Special Occasions
  { category: "special", name: "New Year", date: null },
  { category: "special", name: "Republic Day", date: null },
  { category: "special", name: "Rose Day", date: null },
  { category: "special", name: "Propose Day", date: null },
  { category: "special", name: "Chocolate Day", date: null },
  { category: "special", name: "Teddy Day", date: null },
  { category: "special", name: "Promise Day", date: null },
  { category: "special", name: "Hug Day", date: null },
  { category: "special", name: "Kiss Day", date: null },
  { category: "special", name: "Valentine's Day", date: null },
  { category: "special", name: "Women's Day", date: null },
  { category: "special", name: "Doctor's Day", date: null },
  { category: "special", name: "Mother's Day", date: null },
  { category: "special", name: "Brother's Day", date: null },
  { category: "special", name: "Father's Day", date: null },

  // Occasions
  { category: "occasion", name: "Birthday", date: null },
  { category: "occasion", name: "Anniversary", date: null },
  { category: "occasion", name: "Wedding", date: null },
  { category: "occasion", name: "House Warming", date: null },
  { category: "occasion", name: "New Born Baby", date: null },
  { category: "occasion", name: "Baby Shower", date: null },
  { category: "occasion", name: "Appreciation", date: null },
  { category: "occasion", name: "Cheer Up", date: null },
  { category: "occasion", name: "Congratulations", date: null },
  { category: "occasion", name: "Get Well Soon", date: null },
  { category: "occasion", name: "Love n Romance", date: null },
  { category: "occasion", name: "Thank You", date: null },

  // Type
  { category: "type", name: "Best Seller", date: null },
  { category: "type", name: "Hot Pick", date: null },
  { category: "type", name: "New Arrival", date: null },

  // Relationship
  { category: "relationship", name: "Her", date: null },
  { category: "relationship", name: "Him", date: null },
  { category: "relationship", name: "Friends", date: null },
  { category: "relationship", name: "Wife", date: null },
  { category: "relationship", name: "Husband", date: null },
  { category: "relationship", name: "Kids", date: null },
  { category: "relationship", name: "Boyfriend", date: null },
  { category: "relationship", name: "Girlfriend", date: null },
  { category: "relationship", name: "Mother", date: null },
  { category: "relationship", name: "Father", date: null },

  // Colors
  { category: "color", name: "Red", date: null },
  { category: "color", name: "Pink", date: null },
  { category: "color", name: "White", date: null },
  { category: "color", name: "Yellow", date: null },
  { category: "color", name: "Orange", date: null },
  { category: "color", name: "Purple", date: null },
  { category: "color", name: "Blue", date: null },
  { category: "color", name: "Green", date: null }
],
},
{
title: "Cakes",
items: [
{ category:'SubCategoryFilters',name: "Chocolate Cakes", date: null },
{ category:'SubCategoryFilters',name: "Butterscotch Cakes", date: null },
{ category:'SubCategoryFilters',name: "Black Forest Cakes", date: null },
{ category:'SubCategoryFilters',name: "Fruit Cakes", date: null },
{ category:'SubCategoryFilters',name: "Cheesecakes", date: null },
{ category:'SubCategoryFilters',name: "Pineapple Cakes", date: null },
{ category:'SubCategoryFilters',name: "Red Velvet Cakes", date: null },
{ category:'SubCategoryFilters',name: "Coffee Cakes", date: null },
{ category:'SubCategoryFilters',name: "Strawberry Cakes", date: null },
{ category:'SubCategoryFilters',name: "KitKat Cakes", date: null },
{ category:'SubCategoryFilters',name: "Vanilla Cakes", date: null },
{ category:'SubCategoryFilters',name: "Ferrero Rocher Cakes", date: null },
{ category:'SubCategoryFilters',name: "Blueberry Cakes", date: null },
{ category:'SubCategoryFilters',name: "Rasmalai Cake", date: null },
{ category:'SubCategoryFilters',name: "Chocolate Truffle", date: null },
{ category:'SubCategoryFilters',name: "Photo Cakes", date: null },
{ category:'SubCategoryFilters',name: "Theme Cake", date: null },
{ category:'SubCategoryFilters',name: "Pinata Cake", date: null },
{ category:'SubCategoryFilters',name: "Pull Me Up", date: null },
{ category:'SubCategoryFilters',name: "Doll Cake", date: null },
{ category: "festival", name: "Christmas", date: null },
  { category: "festival", name: "Lohri", date: null },
  { category: "festival", name: "Holi", date: null },
  { category: "festival", name: "Eid Al Fitr", date: null },
  { category: "festival", name: "Rakhi", date: null },

  // Special Occasions
  { category: "special", name: "New Year", date: null },
  { category: "special", name: "Republic Day", date: null },
  { category: "special", name: "Rose Day", date: null },
  { category: "special", name: "Propose Day", date: null },
  { category: "special", name: "Chocolate Day", date: null },
  { category: "special", name: "Teddy Day", date: null },
  { category: "special", name: "Promise Day", date: null },
  { category: "special", name: "Hug Day", date: null },
  { category: "special", name: "Kiss Day", date: null },
  { category: "special", name: "Valentine's Day", date: null },
  { category: "special", name: "Women's Day", date: null },
  { category: "special", name: "Doctor's Day", date: null },
  { category: "special", name: "Mother's Day", date: null },
  { category: "special", name: "Brother's Day", date: null },
  { category: "special", name: "Father's Day", date: null },

  // Occasions
  { category: "occasion", name: "Birthday", date: null },
  { category: "occasion", name: "Anniversary", date: null },
  { category: "occasion", name: "Wedding", date: null },
  { category: "occasion", name: "House Warming", date: null },
  { category: "occasion", name: "New Born Baby", date: null },
  { category: "occasion", name: "Baby Shower", date: null },
  { category: "occasion", name: "Appreciation", date: null },
  { category: "occasion", name: "Cheer Up", date: null },
  { category: "occasion", name: "Congratulations", date: null },
  { category: "occasion", name: "Get Well Soon", date: null },
  { category: "occasion", name: "Love n Romance", date: null },
  { category: "occasion", name: "Thank You", date: null },

  // Type
  { category: "type", name: "Best Seller", date: null },
  { category: "type", name: "Hot Pick", date: null },
  { category: "type", name: "New Arrival", date: null },

  // Relationship
  { category: "relationship", name: "Her", date: null },
  { category: "relationship", name: "Him", date: null },
  { category: "relationship", name: "Friends", date: null },
  { category: "relationship", name: "Wife", date: null },
  { category: "relationship", name: "Husband", date: null },
  { category: "relationship", name: "Kids", date: null },
  { category: "relationship", name: "Boyfriend", date: null },
  { category: "relationship", name: "Girlfriend", date: null },
  { category: "relationship", name: "Mother", date: null },
  { category: "relationship", name: "Father", date: null },

  // Colors
//   { category: "color", name: "Red", date: null },
//   { category: "color", name: "Pink", date: null },
//   { category: "color", name: "White", date: null },
//   { category: "color", name: "Yellow", date: null },
//   { category: "color", name: "Orange", date: null },
//   { category: "color", name: "Purple", date: null },
//   { category: "color", name: "Blue", date: null },
//   { category: "color", name: "Green", date: null }
],
},
{
title: "Plants",
items: [
{ category:'SubCategoryFilters',name: "Bonsai", date: null },
{ category:'SubCategoryFilters',name: "Lucky", date: null },
{ category:'SubCategoryFilters',name: "Jade", date: null },
{ category:'SubCategoryFilters',name: "Money", date: null },
{ category:'SubCategoryFilters',name: "Terrarium", date: null },
{ category:'SubCategoryFilters',name: "Lily", date: null },
{ category:'SubCategoryFilters',name: "Snake", date: null },
{ category:'SubCategoryFilters',name: "Succulents", date: null },
{ category:'SubCategoryFilters',name: "Syngonium", date: null },
{ category: "festival", name: "Christmas", date: null },
  { category: "festival", name: "Lohri", date: null },
  { category: "festival", name: "Holi", date: null },
  { category: "festival", name: "Eid Al Fitr", date: null },
  { category: "festival", name: "Rakhi", date: null },

  // Special Occasions
  { category: "special", name: "New Year", date: null },
  { category: "special", name: "Republic Day", date: null },
  { category: "special", name: "Rose Day", date: null },
  { category: "special", name: "Propose Day", date: null },
  { category: "special", name: "Chocolate Day", date: null },
  { category: "special", name: "Teddy Day", date: null },
  { category: "special", name: "Promise Day", date: null },
  { category: "special", name: "Hug Day", date: null },
  { category: "special", name: "Kiss Day", date: null },
  { category: "special", name: "Valentine's Day", date: null },
  { category: "special", name: "Women's Day", date: null },
  { category: "special", name: "Doctor's Day", date: null },
  { category: "special", name: "Mother's Day", date: null },
  { category: "special", name: "Brother's Day", date: null },
  { category: "special", name: "Father's Day", date: null },

  // Occasions
  { category: "occasion", name: "Birthday", date: null },
  { category: "occasion", name: "Anniversary", date: null },
  { category: "occasion", name: "Wedding", date: null },
  { category: "occasion", name: "House Warming", date: null },
  { category: "occasion", name: "New Born Baby", date: null },
  { category: "occasion", name: "Baby Shower", date: null },
  { category: "occasion", name: "Appreciation", date: null },
  { category: "occasion", name: "Cheer Up", date: null },
  { category: "occasion", name: "Congratulations", date: null },
  { category: "occasion", name: "Get Well Soon", date: null },
  { category: "occasion", name: "Love n Romance", date: null },
  { category: "occasion", name: "Thank You", date: null },

  // Type
  { category: "type", name: "Best Seller", date: null },
  { category: "type", name: "Hot Pick", date: null },
  { category: "type", name: "New Arrival", date: null },

  // Relationship
  { category: "relationship", name: "Her", date: null },
  { category: "relationship", name: "Him", date: null },
  { category: "relationship", name: "Friends", date: null },
  { category: "relationship", name: "Wife", date: null },
  { category: "relationship", name: "Husband", date: null },
  { category: "relationship", name: "Kids", date: null },
  { category: "relationship", name: "Boyfriend", date: null },
  { category: "relationship", name: "Girlfriend", date: null },
  { category: "relationship", name: "Mother", date: null },
  { category: "relationship", name: "Father", date: null },

  // Colors
//   { category: "color", name: "Red", date: null },
//   { category: "color", name: "Pink", date: null },
//   { category: "color", name: "White", date: null },
//   { category: "color", name: "Yellow", date: null },
//   { category: "color", name: "Orange", date: null },
//   { category: "color", name: "Purple", date: null },
//   { category: "color", name: "Blue", date: null },
//   { category: "color", name: "Green", date: null }
],
},
{
title: "Combos",
items: [
{category:'SubCategoryFilters', name: "Hamper", date: null },
{category:'SubCategoryFilters', name: "Flowers & Cakes", date: null },
{category:'SubCategoryFilters', name: "Flowers & Chocolates", date: null },
{category:'SubCategoryFilters', name: "Flowers & Teddy", date: null },
{category:'SubCategoryFilters', name: "All Flowers Combos", date: null },
{category:'SubCategoryFilters', name: "Cakes & Teddy", date: null },
{category:'SubCategoryFilters', name: "All Cake Combos", date: null },
{category:'SubCategoryFilters', name: "Plants & Chocolates", date: null },
{category:'SubCategoryFilters', name: "Plants & Cakes", date: null },
{category:'SubCategoryFilters', name: "Plants & Idols", date: null },
{category:'SubCategoryFilters', name: "All Plant Combos", date: null },
{category:'SubCategoryFilters', name: "Chocolates Gift", date: null },
{ category: "festival", name: "Christmas", date: null },
  { category: "festival", name: "Lohri", date: null },
  { category: "festival", name: "Holi", date: null },
  { category: "festival", name: "Eid Al Fitr", date: null },
  { category: "festival", name: "Rakhi", date: null },

  // Special Occasions
  { category: "special", name: "New Year", date: null },
  { category: "special", name: "Republic Day", date: null },
  { category: "special", name: "Rose Day", date: null },
  { category: "special", name: "Propose Day", date: null },
  { category: "special", name: "Chocolate Day", date: null },
  { category: "special", name: "Teddy Day", date: null },
  { category: "special", name: "Promise Day", date: null },
  { category: "special", name: "Hug Day", date: null },
  { category: "special", name: "Kiss Day", date: null },
  { category: "special", name: "Valentine's Day", date: null },
  { category: "special", name: "Women's Day", date: null },
  { category: "special", name: "Doctor's Day", date: null },
  { category: "special", name: "Mother's Day", date: null },
  { category: "special", name: "Brother's Day", date: null },
  { category: "special", name: "Father's Day", date: null },

  // Occasions
  { category: "occasion", name: "Birthday", date: null },
  { category: "occasion", name: "Anniversary", date: null },
  { category: "occasion", name: "Wedding", date: null },
  { category: "occasion", name: "House Warming", date: null },
  { category: "occasion", name: "New Born Baby", date: null },
  { category: "occasion", name: "Baby Shower", date: null },
  { category: "occasion", name: "Appreciation", date: null },
  { category: "occasion", name: "Cheer Up", date: null },
  { category: "occasion", name: "Congratulations", date: null },
  { category: "occasion", name: "Get Well Soon", date: null },
  { category: "occasion", name: "Love n Romance", date: null },
  { category: "occasion", name: "Thank You", date: null },

  // Type
  { category: "type", name: "Best Seller", date: null },
  { category: "type", name: "Hot Pick", date: null },
  { category: "type", name: "New Arrival", date: null },

  // Relationship
  { category: "relationship", name: "Her", date: null },
  { category: "relationship", name: "Him", date: null },
  { category: "relationship", name: "Friends", date: null },
  { category: "relationship", name: "Wife", date: null },
  { category: "relationship", name: "Husband", date: null },
  { category: "relationship", name: "Kids", date: null },
  { category: "relationship", name: "Boyfriend", date: null },
  { category: "relationship", name: "Girlfriend", date: null },
  { category: "relationship", name: "Mother", date: null },
  { category: "relationship", name: "Father", date: null },

  // Colors
//   { category: "color", name: "Red", date: null },
//   { category: "color", name: "Pink", date: null },
//   { category: "color", name: "White", date: null },
//   { category: "color", name: "Yellow", date: null },
//   { category: "color", name: "Orange", date: null },
//   { category: "color", name: "Purple", date: null },
//   { category: "color", name: "Blue", date: null },
//   { category: "color", name: "Green", date: null }
],
},
{
title: "Festival",
items: [
{ category:'SubCategoryFilters',name: "Christmas", date: "1st Jan" },
{ category:'SubCategoryFilters',name: "Lohri", date: '13th Jan' },
{ category:'SubCategoryFilters',name: "Holi", date: "8th Mar" },
{ category:'SubCategoryFilters',name: "Eid Al Fitr", date: '20th mar' },
{ category:'SubCategoryFilters',name: "Rakhi", date: "28th Aug" },
// { category: "festival", name: "Christmas", date: null },
//   { category: "festival", name: "Lohri", date: null },
//   { category: "festival", name: "Holi", date: null },
//   { category: "festival", name: "Eid Al Fitr", date: null },
//   { category: "festival", name: "Rakhi", date: null },

  // Special Occasions
  { category: "special", name: "New Year", date: null },
  { category: "special", name: "Republic Day", date: null },
  { category: "special", name: "Rose Day", date: null },
  { category: "special", name: "Propose Day", date: null },
  { category: "special", name: "Chocolate Day", date: null },
  { category: "special", name: "Teddy Day", date: null },
  { category: "special", name: "Promise Day", date: null },
  { category: "special", name: "Hug Day", date: null },
  { category: "special", name: "Kiss Day", date: null },
  { category: "special", name: "Valentine's Day", date: null },
  { category: "special", name: "Women's Day", date: null },
  { category: "special", name: "Doctor's Day", date: null },
  { category: "special", name: "Mother's Day", date: null },
  { category: "special", name: "Brother's Day", date: null },
  { category: "special", name: "Father's Day", date: null },

  // Occasions
  { category: "occasion", name: "Birthday", date: null },
  { category: "occasion", name: "Anniversary", date: null },
  { category: "occasion", name: "Wedding", date: null },
  { category: "occasion", name: "House Warming", date: null },
  { category: "occasion", name: "New Born Baby", date: null },
  { category: "occasion", name: "Baby Shower", date: null },
  { category: "occasion", name: "Appreciation", date: null },
  { category: "occasion", name: "Cheer Up", date: null },
  { category: "occasion", name: "Congratulations", date: null },
  { category: "occasion", name: "Get Well Soon", date: null },
  { category: "occasion", name: "Love n Romance", date: null },
  { category: "occasion", name: "Thank You", date: null },

  // Type
  { category: "type", name: "Best Seller", date: null },
  { category: "type", name: "Hot Pick", date: null },
  { category: "type", name: "New Arrival", date: null },

  // Relationship
  { category: "relationship", name: "Her", date: null },
  { category: "relationship", name: "Him", date: null },
  { category: "relationship", name: "Friends", date: null },
  { category: "relationship", name: "Wife", date: null },
  { category: "relationship", name: "Husband", date: null },
  { category: "relationship", name: "Kids", date: null },
  { category: "relationship", name: "Boyfriend", date: null },
  { category: "relationship", name: "Girlfriend", date: null },
  { category: "relationship", name: "Mother", date: null },
  { category: "relationship", name: "Father", date: null },

  // Colors
  { category: "color", name: "Red", date: null },
  { category: "color", name: "Pink", date: null },
  { category: "color", name: "White", date: null },
  { category: "color", name: "Yellow", date: null },
  { category: "color", name: "Orange", date: null },
  { category: "color", name: "Purple", date: null },
  { category: "color", name: "Blue", date: null },
  { category: "color", name: "Green", date: null }


],
},
{
title: "Special Occasion",
items: [
{category:'SubCategoryFilters', name: "New Year", date: "1st Jan" },
{category:'SubCategoryFilters', name: "Republic Day", date: "26th Jan" },
{category:'SubCategoryFilters', name: "Rose Day", date: "7th Fab" },
{category:'SubCategoryFilters', name: "Propose Day", date: "8th Fab"},
{category:'SubCategoryFilters', name: "Chocolate Day", date: "9th Fab" },
{category:'SubCategoryFilters', name: "Teddy Day", date: "10th Fab" },
{category:'SubCategoryFilters', name: "Promise Day", date: "11th Fab"},
{category:'SubCategoryFilters', name: "Hug Day", date: "12th Fab" },
{category:'SubCategoryFilters', name: "Kiss Day", date: "13th Fab" },
{category:'SubCategoryFilters', name: "Valentine's Day", date: "14th Fab"  },
{category:'SubCategoryFilters', name: "Womens Day", date: '8th Mar'},
{category:'SubCategoryFilters', name: "Doctors Day", date: '30th Mar'},
{category:'SubCategoryFilters', name: "Mothers Day", date: "10th May" },
{category:'SubCategoryFilters', name: "Brother's Day", date:  "10th May" },
{category:'SubCategoryFilters', name: "Father's Day", date: "21st Jun" },
{ category: "festival", name: "Christmas", date: null },
  { category: "festival", name: "Lohri", date: null },
  { category: "festival", name: "Holi", date: null },
  { category: "festival", name: "Eid Al Fitr", date: null },
  { category: "festival", name: "Rakhi", date: null },

  // Special Occasions
//   { category: "special", name: "New Year", date: null },
//   { category: "special", name: "Republic Day", date: null },
//   { category: "special", name: "Rose Day", date: null },
//   { category: "special", name: "Propose Day", date: null },
//   { category: "special", name: "Chocolate Day", date: null },
//   { category: "special", name: "Teddy Day", date: null },
//   { category: "special", name: "Promise Day", date: null },
//   { category: "special", name: "Hug Day", date: null },
//   { category: "special", name: "Kiss Day", date: null },
//   { category: "special", name: "Valentine's Day", date: null },
//   { category: "special", name: "Women's Day", date: null },
//   { category: "special", name: "Doctor's Day", date: null },
//   { category: "special", name: "Mother's Day", date: null },
//   { category: "special", name: "Brother's Day", date: null },
//   { category: "special", name: "Father's Day", date: null },

  // Occasions
  { category: "occasion", name: "Birthday", date: null },
  { category: "occasion", name: "Anniversary", date: null },
  { category: "occasion", name: "Wedding", date: null },
  { category: "occasion", name: "House Warming", date: null },
  { category: "occasion", name: "New Born Baby", date: null },
  { category: "occasion", name: "Baby Shower", date: null },
  { category: "occasion", name: "Appreciation", date: null },
  { category: "occasion", name: "Cheer Up", date: null },
  { category: "occasion", name: "Congratulations", date: null },
  { category: "occasion", name: "Get Well Soon", date: null },
  { category: "occasion", name: "Love n Romance", date: null },
  { category: "occasion", name: "Thank You", date: null },

  // Type
  { category: "type", name: "Best Seller", date: null },
  { category: "type", name: "Hot Pick", date: null },
  { category: "type", name: "New Arrival", date: null },

  // Relationship
  { category: "relationship", name: "Her", date: null },
  { category: "relationship", name: "Him", date: null },
  { category: "relationship", name: "Friends", date: null },
  { category: "relationship", name: "Wife", date: null },
  { category: "relationship", name: "Husband", date: null },
  { category: "relationship", name: "Kids", date: null },
  { category: "relationship", name: "Boyfriend", date: null },
  { category: "relationship", name: "Girlfriend", date: null },
  { category: "relationship", name: "Mother", date: null },
  { category: "relationship", name: "Father", date: null },

  // Colors
//   { category: "color", name: "Red", date: null },
//   { category: "color", name: "Pink", date: null },
//   { category: "color", name: "White", date: null },
//   { category: "color", name: "Yellow", date: null },
//   { category: "color", name: "Orange", date: null },
//   { category: "color", name: "Purple", date: null },
//   { category: "color", name: "Blue", date: null },
//   { category: "color", name: "Green", date: null }
],
},
{
title: "Occasion",
items: [
{ category:'SubCategoryFilters',name: "Birthday", date: null },
{ category:'SubCategoryFilters',name: "Anniversary", date: null },
{ category:'SubCategoryFilters',name: "Wedding", date: null },
{ category:'SubCategoryFilters',name: "House Warming", date: null },
{ category:'SubCategoryFilters',name: "New Born Baby", date: null },
{ category:'SubCategoryFilters',name: "Baby Shower", date: null },
{ category:'SubCategoryFilters',name: "Appreciation", date: null },
{ category:'SubCategoryFilters',name: "Cheer Up", date: null },
{ category:'SubCategoryFilters',name: "Congratulations", date: null },
{ category:'SubCategoryFilters',name: "Get Well Soon", date: null },
{ category:'SubCategoryFilters',name: "Love n Romance", date: null },
{ category:'SubCategoryFilters',name: "Thank You", date: null },
{ category: "festival", name: "Christmas", date: null },
  { category: "festival", name: "Lohri", date: null },
  { category: "festival", name: "Holi", date: null },
  { category: "festival", name: "Eid Al Fitr", date: null },
  { category: "festival", name: "Rakhi", date: null },

  // Special Occasions
  { category: "special", name: "New Year", date: null },
  { category: "special", name: "Republic Day", date: null },
  { category: "special", name: "Rose Day", date: null },
  { category: "special", name: "Propose Day", date: null },
  { category: "special", name: "Chocolate Day", date: null },
  { category: "special", name: "Teddy Day", date: null },
  { category: "special", name: "Promise Day", date: null },
  { category: "special", name: "Hug Day", date: null },
  { category: "special", name: "Kiss Day", date: null },
  { category: "special", name: "Valentine's Day", date: null },
  { category: "special", name: "Women's Day", date: null },
  { category: "special", name: "Doctor's Day", date: null },
  { category: "special", name: "Mother's Day", date: null },
  { category: "special", name: "Brother's Day", date: null },
  { category: "special", name: "Father's Day", date: null },

  // Occasions
//   { category: "occasion", name: "Birthday", date: null },
//   { category: "occasion", name: "Anniversary", date: null },
//   { category: "occasion", name: "Wedding", date: null },
//   { category: "occasion", name: "House Warming", date: null },
//   { category: "occasion", name: "New Born Baby", date: null },
//   { category: "occasion", name: "Baby Shower", date: null },
//   { category: "occasion", name: "Appreciation", date: null },
//   { category: "occasion", name: "Cheer Up", date: null },
//   { category: "occasion", name: "Congratulations", date: null },
//   { category: "occasion", name: "Get Well Soon", date: null },
//   { category: "occasion", name: "Love n Romance", date: null },
//   { category: "occasion", name: "Thank You", date: null },

  // Type
  { category: "type", name: "Best Seller", date: null },
  { category: "type", name: "Hot Pick", date: null },
  { category: "type", name: "New Arrival", date: null },

  // Relationship
  { category: "relationship", name: "Her", date: null },
  { category: "relationship", name: "Him", date: null },
  { category: "relationship", name: "Friends", date: null },
  { category: "relationship", name: "Wife", date: null },
  { category: "relationship", name: "Husband", date: null },
  { category: "relationship", name: "Kids", date: null },
  { category: "relationship", name: "Boyfriend", date: null },
  { category: "relationship", name: "Girlfriend", date: null },
  { category: "relationship", name: "Mother", date: null },
  { category: "relationship", name: "Father", date: null },

  // Colors
//   { category: "color", name: "Red", date: null },
//   { category: "color", name: "Pink", date: null },
//   { category: "color", name: "White", date: null },
//   { category: "color", name: "Yellow", date: null },
//   { category: "color", name: "Orange", date: null },
//   { category: "color", name: "Purple", date: null },
//   { category: "color", name: "Blue", date: null },
//   { category: "color", name: "Green", date: null }
],
},
{
title: "Loved Ones",
items: [
{ category:'SubCategoryFilters',name: "Her", date: null },
{ category:'SubCategoryFilters',name: "Him", date: null },
{ category:'SubCategoryFilters',name: "Friends", date: null },
{ category:'SubCategoryFilters',name: "Wife", date: null },
{ category:'SubCategoryFilters',name: "Husband", date: null },
{ category:'SubCategoryFilters',name: "Kids", date: null },
{ category:'SubCategoryFilters',name: "Boyfriend", date: null },
{ category:'SubCategoryFilters',name: "Girlfriend", date: null },
{ category:'SubCategoryFilters',name: "Mother", date: null },
{ category:'SubCategoryFilters',name: "Father", date: null },
{ category: "festival", name: "Christmas", date: null },
  { category: "festival", name: "Lohri", date: null },
  { category: "festival", name: "Holi", date: null },
  { category: "festival", name: "Eid Al Fitr", date: null },
  { category: "festival", name: "Rakhi", date: null },

  // Special Occasions
  { category: "special", name: "New Year", date: null },
  { category: "special", name: "Republic Day", date: null },
  { category: "special", name: "Rose Day", date: null },
  { category: "special", name: "Propose Day", date: null },
  { category: "special", name: "Chocolate Day", date: null },
  { category: "special", name: "Teddy Day", date: null },
  { category: "special", name: "Promise Day", date: null },
  { category: "special", name: "Hug Day", date: null },
  { category: "special", name: "Kiss Day", date: null },
  { category: "special", name: "Valentine's Day", date: null },
  { category: "special", name: "Women's Day", date: null },
  { category: "special", name: "Doctor's Day", date: null },
  { category: "special", name: "Mother's Day", date: null },
  { category: "special", name: "Brother's Day", date: null },
  { category: "special", name: "Father's Day", date: null },

  // Occasions
  { category: "occasion", name: "Birthday", date: null },
  { category: "occasion", name: "Anniversary", date: null },
  { category: "occasion", name: "Wedding", date: null },
  { category: "occasion", name: "House Warming", date: null },
  { category: "occasion", name: "New Born Baby", date: null },
  { category: "occasion", name: "Baby Shower", date: null },
  { category: "occasion", name: "Appreciation", date: null },
  { category: "occasion", name: "Cheer Up", date: null },
  { category: "occasion", name: "Congratulations", date: null },
  { category: "occasion", name: "Get Well Soon", date: null },
  { category: "occasion", name: "Love n Romance", date: null },
  { category: "occasion", name: "Thank You", date: null },

  // Type
  { category: "type", name: "Best Seller", date: null },
  { category: "type", name: "Hot Pick", date: null },
  { category: "type", name: "New Arrival", date: null },

  // Relationship
  { category: "relationship", name: "Her", date: null },
  { category: "relationship", name: "Him", date: null },
  { category: "relationship", name: "Friends", date: null },
  { category: "relationship", name: "Wife", date: null },
  { category: "relationship", name: "Husband", date: null },
  { category: "relationship", name: "Kids", date: null },
  { category: "relationship", name: "Boyfriend", date: null },
  { category: "relationship", name: "Girlfriend", date: null },
  { category: "relationship", name: "Mother", date: null },
  { category: "relationship", name: "Father", date: null },

  // Colors
//   { category: "color", name: "Red", date: null },
//   { category: "color", name: "Pink", date: null },
//   { category: "color", name: "White", date: null },
//   { category: "color", name: "Yellow", date: null },
//   { category: "color", name: "Orange", date: null },
//   { category: "color", name: "Purple", date: null },
//   { category: "color", name: "Blue", date: null },
//   { category: "color", name: "Green", date: null }
],
},
{
title: "Internship Program",
url: "https://www.redheart.in/hiring-for-internship",
items: [],
},
];