
export const menuData = [
{
title:"Category",
items:[
{name: "Plants", date: null },
{name: "Flowers", date: null },
{name: "Cakes", date: null },
{name: "Gifts", date: null },
{name: "Hampers", date: null },
{name: "Chocolate Gifts", date: null },
{name: "Combos", date: null },
]
},
{
title: "Flowers",
items: [
{ name: "Roses", date: null },
{ name: "Lilies", date: null },
{ name: "Orchids", date: null },
{ name: "Mixed", date: null },
{ name: "Carnation", date: null },
{ name: "Gerbera", date: null },
],
},
{
title: "Cakes",
items: [
{ name: "Chocolate Cakes", date: null },
{ name: "Butterscotch Cakes", date: null },
{ name: "Black Forest Cakes", date: null },
{ name: "Fruit Cakes", date: null },
{ name: "Cheesecakes", date: null },
{ name: "Pineapple Cakes", date: null },
{ name: "Red Velvet Cakes", date: null },
{ name: "Coffee Cakes", date: null },
{ name: "Strawberry Cakes", date: null },
{ name: "KitKat Cakes", date: null },
{ name: "Vanilla Cakes", date: null },
{ name: "Ferrero Rocher Cakes", date: null },
{ name: "Blueberry Cakes", date: null },
{ name: "Rasmalai Cake", date: null },
{ name: "Chocolate Truffle", date: null },
{ name: "Photo Cakes", date: null },
{ name: "Theme Cake", date: null },
{ name: "Pinata Cake", date: null },
{ name: "Pull Me Up", date: null },
{ name: "Doll Cake", date: null },
],
},
{
title: "Plants",
items: [
{ name: "Bonsai", date: null },
{ name: "Lucky", date: null },
{ name: "Jade", date: null },
{ name: "Money", date: null },
{ name: "Terrarium", date: null },
{ name: "Lily", date: null },
{ name: "Snake", date: null },
{ name: "Succulents", date: null },
{ name: "Syngonium", date: null },
],
},
{
title: "Combos",
items: [
{ name: "Hamper", date: null },
{ name: "Flowers & Cakes", date: null },
{ name: "Flowers & Chocolates", date: null },
{ name: "Flowers & Teddy", date: null },
{ name: "All Flowers Combos", date: null },
{ name: "Cakes & Teddy", date: null },
{ name: "All Cake Combos", date: null },
{ name: "Plants & Chocolates", date: null },
{ name: "Plants & Cakes", date: null },
{ name: "Plants & Idols", date: null },
{ name: "All Plant Combos", date: null },
{ name: "Chocolates Gift", date: null },
],
},
{
title: "Festival",
items: [
{ name: "Christmas", date: "1st Jan" },
{ name: "Lohri", date: '13th Jan' },
{ name: "Holi", date: "8th Mar" },
{ name: "Eid Al Fitr", date: '20th mar' },
{ name: "Rakhi", date: "28th Aug" },


],
},
{
title: "Special Occasion",
items: [
{ name: "New Year", date: "1st Jan" },
{ name: "Republic Day", date: "26th Jan" },
{ name: "Rose Day", date: "7th Fab" },
{ name: "Propose Day", date: "8th Fab"},
{ name: "Chocolate Day", date: "9th Fab" },
{ name: "Teddy Day", date: "10th Fab" },
{ name: "Promise Day", date: "11th Fab"},
{ name: "Hug Day", date: "12th Fab" },
{ name: "Kiss Day", date: "13th Fab" },
{ name: "Valentine's Day", date: "14th Fab"  },
{ name: "Womens Day", date: '8th Mar'},
{ name: "Doctors Day", date: '30th Mar'},
{ name: "Mothers Day", date: "10th May" },
{ name: "Brother's Day", date:  "10th May" },
{ name: "Father's Day", date: "21st Jun" },
],
},
{
title: "Occasion",
items: [
{ name: "Birthday", date: null },
{ name: "Anniversary", date: null },
{ name: "Wedding", date: null },
{ name: "House Warming", date: null },
{ name: "New Born Baby", date: null },
{ name: "Baby Shower", date: null },
{ name: "Appreciation", date: null },
{ name: "Cheer Up", date: null },
{ name: "Congratulations", date: null },
{ name: "Get Well Soon", date: null },
{ name: "Love n Romance", date: null },
{ name: "Thank You", date: null },
],
},
{
title: "Loved Ones",
items: [
{ name: "Her", date: null },
{ name: "Him", date: null },
{ name: "Friends", date: null },
{ name: "Wife", date: null },
{ name: "Husband", date: null },
{ name: "Kids", date: null },
{ name: "Boyfriend", date: null },
{ name: "Girlfriend", date: null },
{ name: "Mother", date: null },
{ name: "Father", date: null },
],
},
];