/**
 * SEO meta titles and descriptions for every category / subcategory page.
 * Key format: "categorySlug" or "categorySlug/subcategorySlug"
 *
 * Title:       50–60 chars  — keyword | value prop | brand
 * Description: 140–160 chars — keyword + USP + CTA
 */

export const PAGE_META_MAP = {

  // ── FLOWERS ────────────────────────────────────────────────────────────────
  'florist-near-me': {
    title:       'Online Flower Delivery | Same Day Fresh Flowers | RedHeart',
    description: 'Order fresh flowers online with same-day & midnight delivery across India. Roses, lilies, bouquets & more from ₹399. Free shipping on select orders. Shop RedHeart now!',
  },
  'flowers': {
    title:       'Online Flower Delivery | Same Day Fresh Flowers | RedHeart',
    description: 'Buy fresh flowers online in India. Same-day delivery of roses, lilies, sunflowers & bouquets starting ₹399. Midnight delivery available. Order now at RedHeart!',
  },
  'florist-near-me/bouquets': {
    title:       'Fresh Flower Bouquets Online | Same Day Delivery | RedHeart',
    description: 'Shop beautiful fresh flower bouquets online. Hand-tied roses, lilies, mixed bouquets & more with same-day delivery starting ₹499. Order at RedHeart today!',
  },
  'flowers/bouquets': {
    title:       'Fresh Flower Bouquets Online | Same Day Delivery | RedHeart',
    description: 'Shop beautiful fresh flower bouquets online. Hand-tied roses, lilies, mixed bouquets & more with same-day delivery starting ₹499. Order at RedHeart today!',
  },
  'florist-near-me/hot-picks': {
    title:       'Hot Pick Flowers | Trending Bouquets Online | RedHeart',
    description: 'Discover our most trending flower bouquets this season. Fresh hot-pick floral arrangements with same-day delivery across India. Starting ₹399. Shop RedHeart!',
  },
  'flowers/hot-picks': {
    title:       'Hot Pick Flowers | Trending Bouquets Online | RedHeart',
    description: 'Discover our most trending flower bouquets this season. Fresh hot-pick floral arrangements with same-day delivery across India. Starting ₹399. Shop RedHeart!',
  },
  'florist-near-me/best-sellers': {
    title:       'Best Selling Flowers Online | Top Bouquets | RedHeart',
    description: 'Shop our best-selling flower bouquets loved by thousands. Fresh roses, lilies & mixed arrangements with same-day delivery across India. Order at RedHeart!',
  },
  'flowers/best-sellers': {
    title:       'Best Selling Flowers Online | Top Bouquets | RedHeart',
    description: 'Shop our best-selling flower bouquets loved by thousands. Fresh roses, lilies & mixed arrangements with same-day delivery across India. Order at RedHeart!',
  },
  'florist-near-me/new-arrivals': {
    title:       'New Arrival Flowers | Latest Bouquets Online | RedHeart',
    description: 'Explore our latest flower collections — fresh new arrivals delivered same-day. Unique bouquets & floral arrangements online from ₹399. Shop at RedHeart!',
  },
  'flowers/new-arrivals': {
    title:       'New Arrival Flowers | Latest Bouquets Online | RedHeart',
    description: 'Explore our latest flower collections — fresh new arrivals delivered same-day. Unique bouquets & floral arrangements online from ₹399. Shop at RedHeart!',
  },
  // Varieties
  'florist-near-me/roses':              { title: 'Send Roses Online | Fresh Rose Bouquets | RedHeart', description: 'Buy fresh roses online — red, pink, white & mixed rose bouquets with same-day delivery. Perfect for love & romance. Starting ₹399. Order at RedHeart!' },
  'flowers/roses':                      { title: 'Send Roses Online | Fresh Rose Bouquets | RedHeart', description: 'Buy fresh roses online — red, pink, white & mixed rose bouquets with same-day delivery. Perfect for love & romance. Starting ₹399. Order at RedHeart!' },
  'florist-near-me/lilies':             { title: 'Buy Lilies Online | Fresh Lily Bouquets | RedHeart', description: 'Order fresh lilies online — white, pink & mixed lily bouquets with same-day delivery across India. Elegant flowers from ₹449. Shop at RedHeart now!' },
  'flowers/lilies':                     { title: 'Buy Lilies Online | Fresh Lily Bouquets | RedHeart', description: 'Order fresh lilies online — white, pink & mixed lily bouquets with same-day delivery across India. Elegant flowers from ₹449. Shop at RedHeart now!' },
  'florist-near-me/carnations':         { title: 'Buy Carnations Online | Fresh Carnation Bouquets | RedHeart', description: 'Order fresh carnations online — colourful carnation bouquets with same-day delivery. Perfect for any occasion from ₹399. Shop carnations at RedHeart!' },
  'flowers/carnations':                 { title: 'Buy Carnations Online | Fresh Carnation Bouquets | RedHeart', description: 'Order fresh carnations online — colourful carnation bouquets with same-day delivery. Perfect for any occasion from ₹399. Shop carnations at RedHeart!' },
  'florist-near-me/roses-and-carnation':{ title: 'Roses & Carnation Bouquets Online | RedHeart', description: 'Buy beautiful roses & carnation mixed bouquets online. Same-day delivery across India. A stunning combination for every special occasion. Order at RedHeart!' },
  'flowers/roses-and-carnation':        { title: 'Roses & Carnation Bouquets Online | RedHeart', description: 'Buy beautiful roses & carnation mixed bouquets online. Same-day delivery across India. A stunning combination for every special occasion. Order at RedHeart!' },
  'florist-near-me/roses-and-lily':     { title: 'Roses & Lily Bouquets Online | RedHeart', description: 'Shop fresh roses & lily mixed arrangements online. Elegant bouquets with same-day delivery across India. Perfect for anniversaries & romance. Order at RedHeart!' },
  'flowers/roses-and-lily':             { title: 'Roses & Lily Bouquets Online | RedHeart', description: 'Shop fresh roses & lily mixed arrangements online. Elegant bouquets with same-day delivery across India. Perfect for anniversaries & romance. Order at RedHeart!' },
  // Flower Occasions
  'florist-near-me/birthday':           { title: 'Birthday Flowers | Same Day Delivery | RedHeart', description: 'Surprise someone on their birthday with fresh flower bouquets. Same-day & midnight birthday flower delivery from ₹399. Free card included. Order at RedHeart!' },
  'flowers/birthday':                   { title: 'Birthday Flowers | Same Day Delivery | RedHeart', description: 'Surprise someone on their birthday with fresh flower bouquets. Same-day & midnight birthday flower delivery from ₹399. Free card included. Order at RedHeart!' },
  'florist-near-me/anniversary':        { title: 'Anniversary Flowers | Romantic Bouquets | RedHeart', description: 'Celebrate your anniversary with stunning fresh flower bouquets. Roses, lilies & mixed arrangements for same-day delivery. Order anniversary flowers at RedHeart!' },
  'flowers/anniversary':                { title: 'Anniversary Flowers | Romantic Bouquets | RedHeart', description: 'Celebrate your anniversary with stunning fresh flower bouquets. Roses, lilies & mixed arrangements for same-day delivery. Order anniversary flowers at RedHeart!' },
  'florist-near-me/wedding':            { title: 'Wedding Flowers | Fresh Bridal Bouquets | RedHeart', description: 'Beautiful wedding flower arrangements — bridal bouquets, decor flowers & more. Same-day delivery for your special day. Order wedding flowers at RedHeart!' },
  'flowers/wedding':                    { title: 'Wedding Flowers | Fresh Bridal Bouquets | RedHeart', description: 'Beautiful wedding flower arrangements — bridal bouquets, decor flowers & more. Same-day delivery for your special day. Order wedding flowers at RedHeart!' },
  'florist-near-me/valentine':          { title: "Valentine's Day Flowers | Red Roses | RedHeart", description: "Send love with fresh Valentine's Day flowers — red roses, heart bouquets & romantic arrangements. Same-day delivery. Order Valentine flowers at RedHeart!" },
  'flowers/valentine':                  { title: "Valentine's Day Flowers | Red Roses | RedHeart", description: "Send love with fresh Valentine's Day flowers — red roses, heart bouquets & romantic arrangements. Same-day delivery. Order Valentine flowers at RedHeart!" },
  'florist-near-me/love-and-romance':   { title: 'Love & Romance Flowers | Red Roses | RedHeart', description: 'Express your love with romantic flower bouquets. Fresh red roses, pink roses & heart arrangements delivered same-day. Order love flowers at RedHeart!' },
  'flowers/love-and-romance':           { title: 'Love & Romance Flowers | Red Roses | RedHeart', description: 'Express your love with romantic flower bouquets. Fresh red roses, pink roses & heart arrangements delivered same-day. Order love flowers at RedHeart!' },
  'florist-near-me/congratulations':    { title: 'Congratulations Flowers | Fresh Bouquets | RedHeart', description: 'Send congratulations with beautiful fresh flower bouquets. Bright, cheerful arrangements for achievements & celebrations. Same-day delivery at RedHeart!' },
  'flowers/congratulations':            { title: 'Congratulations Flowers | Fresh Bouquets | RedHeart', description: 'Send congratulations with beautiful fresh flower bouquets. Bright, cheerful arrangements for achievements & celebrations. Same-day delivery at RedHeart!' },
  'florist-near-me/get-well-soon':      { title: 'Get Well Soon Flowers | Fresh Cheerful Bouquets | RedHeart', description: 'Brighten someone\'s day with get well soon flowers. Fresh, uplifting bouquets with same-day hospital & home delivery. Order at RedHeart from ₹399!' },
  'flowers/get-well-soon':              { title: 'Get Well Soon Flowers | Fresh Cheerful Bouquets | RedHeart', description: 'Brighten someone\'s day with get well soon flowers. Fresh, uplifting bouquets with same-day hospital & home delivery. Order at RedHeart from ₹399!' },
  'florist-near-me/thank-you':          { title: 'Thank You Flowers | Fresh Bouquets Online | RedHeart', description: 'Say thank you with beautiful fresh flowers. Heartfelt bouquets & arrangements with same-day delivery across India from ₹399. Order at RedHeart now!' },
  'flowers/thank-you':                  { title: 'Thank You Flowers | Fresh Bouquets Online | RedHeart', description: 'Say thank you with beautiful fresh flowers. Heartfelt bouquets & arrangements with same-day delivery across India from ₹399. Order at RedHeart now!' },
  'florist-near-me/house-warming':      { title: 'House Warming Flowers | Floral Gifts | RedHeart', description: 'Welcome someone to their new home with fresh house warming flowers. Beautiful bouquets & arrangements with same-day delivery. Order at RedHeart!' },
  'flowers/house-warming':              { title: 'House Warming Flowers | Floral Gifts | RedHeart', description: 'Welcome someone to their new home with fresh house warming flowers. Beautiful bouquets & arrangements with same-day delivery. Order at RedHeart!' },
  'florist-near-me/baby-shower':        { title: 'Baby Shower Flowers | Fresh Floral Gifts | RedHeart', description: 'Celebrate a new arrival with beautiful baby shower flowers. Soft, elegant bouquets with same-day delivery across India. Order baby shower flowers at RedHeart!' },
  'flowers/baby-shower':                { title: 'Baby Shower Flowers | Fresh Floral Gifts | RedHeart', description: 'Celebrate a new arrival with beautiful baby shower flowers. Soft, elegant bouquets with same-day delivery across India. Order baby shower flowers at RedHeart!' },
  'florist-near-me/new-born-baby':      { title: 'New Born Baby Flowers | Soft Fresh Bouquets | RedHeart', description: 'Welcome the newborn with soft, fresh flowers. Delicate arrangements for new baby celebrations with same-day delivery. Order at RedHeart from ₹399!' },
  'flowers/new-born-baby':              { title: 'New Born Baby Flowers | Soft Fresh Bouquets | RedHeart', description: 'Welcome the newborn with soft, fresh flowers. Delicate arrangements for new baby celebrations with same-day delivery. Order at RedHeart from ₹399!' },
  'florist-near-me/appreciation':       { title: 'Appreciation Flowers | Fresh Bouquets | RedHeart', description: 'Show appreciation with beautiful fresh flower bouquets. Elegant arrangements for colleagues, friends & family. Same-day delivery. Order at RedHeart!' },
  'flowers/appreciation':               { title: 'Appreciation Flowers | Fresh Bouquets | RedHeart', description: 'Show appreciation with beautiful fresh flower bouquets. Elegant arrangements for colleagues, friends & family. Same-day delivery. Order at RedHeart!' },
  'florist-near-me/cheer-up':           { title: 'Cheer Up Flowers | Bright Happy Bouquets | RedHeart', description: 'Cheer someone up with a beautiful flower bouquet. Bright, uplifting fresh flowers delivered same-day across India from ₹399. Order at RedHeart now!' },
  'flowers/cheer-up':                   { title: 'Cheer Up Flowers | Bright Happy Bouquets | RedHeart', description: 'Cheer someone up with a beautiful flower bouquet. Bright, uplifting fresh flowers delivered same-day across India from ₹399. Order at RedHeart now!' },
  // Flower Relationships
  'florist-near-me/for-her':            { title: 'Flowers for Her | Fresh Bouquets for Women | RedHeart', description: 'Send beautiful flowers for her — roses, lilies & elegant bouquets. Perfect gifts for girlfriend, wife, mother & sister. Same-day delivery. Order at RedHeart!' },
  'flowers/for-her':                    { title: 'Flowers for Her | Fresh Bouquets for Women | RedHeart', description: 'Send beautiful flowers for her — roses, lilies & elegant bouquets. Perfect gifts for girlfriend, wife, mother & sister. Same-day delivery. Order at RedHeart!' },
  'florist-near-me/for-him':            { title: 'Flowers for Him | Fresh Bouquets for Men | RedHeart', description: 'Send flowers for him — bold, premium bouquets for boyfriend, husband, father & friends. Same-day delivery across India from ₹399. Order at RedHeart!' },
  'flowers/for-him':                    { title: 'Flowers for Him | Fresh Bouquets for Men | RedHeart', description: 'Send flowers for him — bold, premium bouquets for boyfriend, husband, father & friends. Same-day delivery across India from ₹399. Order at RedHeart!' },
  'florist-near-me/for-wife':           { title: 'Flowers for Wife | Romantic Bouquets | RedHeart', description: 'Surprise your wife with stunning fresh flower bouquets. Romantic roses, lilies & premium arrangements. Same-day & midnight delivery. Order at RedHeart!' },
  'flowers/for-wife':                   { title: 'Flowers for Wife | Romantic Bouquets | RedHeart', description: 'Surprise your wife with stunning fresh flower bouquets. Romantic roses, lilies & premium arrangements. Same-day & midnight delivery. Order at RedHeart!' },
  'florist-near-me/for-husband':        { title: 'Flowers for Husband | Fresh Bouquets | RedHeart', description: 'Gift your husband fresh flowers — premium bouquets & arrangements with same-day & midnight delivery across India. Express your love at RedHeart!' },
  'flowers/for-husband':                { title: 'Flowers for Husband | Fresh Bouquets | RedHeart', description: 'Gift your husband fresh flowers — premium bouquets & arrangements with same-day & midnight delivery across India. Express your love at RedHeart!' },
  'florist-near-me/for-mother':         { title: 'Flowers for Mother | Fresh Bouquets | RedHeart', description: 'Show your mother love with beautiful fresh flowers. Roses, lilies & mixed bouquets with same-day delivery. Perfect for any occasion. Order at RedHeart!' },
  'flowers/for-mother':                 { title: 'Flowers for Mother | Fresh Bouquets | RedHeart', description: 'Show your mother love with beautiful fresh flowers. Roses, lilies & mixed bouquets with same-day delivery. Perfect for any occasion. Order at RedHeart!' },
  'florist-near-me/for-father':         { title: 'Flowers for Father | Fresh Bouquets | RedHeart', description: 'Gift your father a beautiful fresh flower bouquet. Elegant arrangements delivered same-day across India. Show dad you care. Order flowers at RedHeart!' },
  'flowers/for-father':                 { title: 'Flowers for Father | Fresh Bouquets | RedHeart', description: 'Gift your father a beautiful fresh flower bouquet. Elegant arrangements delivered same-day across India. Show dad you care. Order flowers at RedHeart!' },
  'florist-near-me/for-girlfriend':     { title: 'Flowers for Girlfriend | Romantic Bouquets | RedHeart', description: 'Impress your girlfriend with a stunning fresh flower bouquet. Red roses, pink bouquets & heart arrangements with same-day delivery. Order at RedHeart!' },
  'flowers/for-girlfriend':             { title: 'Flowers for Girlfriend | Romantic Bouquets | RedHeart', description: 'Impress your girlfriend with a stunning fresh flower bouquet. Red roses, pink bouquets & heart arrangements with same-day delivery. Order at RedHeart!' },
  'florist-near-me/for-boyfriend':      { title: 'Flowers for Boyfriend | Fresh Bouquets | RedHeart', description: 'Surprise your boyfriend with fresh flowers — bold roses & premium bouquets with same-day & midnight delivery across India. Order at RedHeart!' },
  'flowers/for-boyfriend':              { title: 'Flowers for Boyfriend | Fresh Bouquets | RedHeart', description: 'Surprise your boyfriend with fresh flowers — bold roses & premium bouquets with same-day & midnight delivery across India. Order at RedHeart!' },
  'florist-near-me/for-friends':        { title: 'Flowers for Friends | Fresh Bouquets | RedHeart', description: 'Send cheerful fresh flowers to your friends. Colourful bouquets & fun arrangements with same-day delivery from ₹399. Order friendship flowers at RedHeart!' },
  'flowers/for-friends':                { title: 'Flowers for Friends | Fresh Bouquets | RedHeart', description: 'Send cheerful fresh flowers to your friends. Colourful bouquets & fun arrangements with same-day delivery from ₹399. Order friendship flowers at RedHeart!' },
  'florist-near-me/for-kids':           { title: 'Flowers for Kids | Fun Colourful Bouquets | RedHeart', description: 'Delight kids with bright, colourful flower bouquets. Fun floral arrangements with same-day delivery across India from ₹399. Order at RedHeart now!' },
  'flowers/for-kids':                   { title: 'Flowers for Kids | Fun Colourful Bouquets | RedHeart', description: 'Delight kids with bright, colourful flower bouquets. Fun floral arrangements with same-day delivery across India from ₹399. Order at RedHeart now!' },
  // Flower Festivals
  'florist-near-me/valentines-day':     { title: "Valentine's Day Flowers | Roses & Bouquets | RedHeart", description: "Order Valentine's Day flowers online — red roses, heart bouquets & romantic floral gifts. Same-day & midnight delivery. Shop Valentine flowers at RedHeart!" },
  'flowers/valentines-day':             { title: "Valentine's Day Flowers | Roses & Bouquets | RedHeart", description: "Order Valentine's Day flowers online — red roses, heart bouquets & romantic floral gifts. Same-day & midnight delivery. Shop Valentine flowers at RedHeart!" },
  'florist-near-me/rose-day':           { title: 'Rose Day Flowers | Fresh Roses Online | RedHeart', description: 'Celebrate Rose Day with the freshest roses delivered same-day. Red, pink, white & yellow roses from ₹399. Make it special. Order rose day flowers at RedHeart!' },
  'flowers/rose-day':                   { title: 'Rose Day Flowers | Fresh Roses Online | RedHeart', description: 'Celebrate Rose Day with the freshest roses delivered same-day. Red, pink, white & yellow roses from ₹399. Make it special. Order rose day flowers at RedHeart!' },
  'florist-near-me/mothers-day':        { title: "Mother's Day Flowers | Fresh Bouquets | RedHeart", description: "Celebrate Mother's Day with stunning fresh flower bouquets. Roses, lilies & premium arrangements with same-day delivery. Order Mother's Day flowers at RedHeart!" },
  'flowers/mothers-day':                { title: "Mother's Day Flowers | Fresh Bouquets | RedHeart", description: "Celebrate Mother's Day with stunning fresh flower bouquets. Roses, lilies & premium arrangements with same-day delivery. Order Mother's Day flowers at RedHeart!" },
  'florist-near-me/womens-day':         { title: "Women's Day Flowers | Fresh Bouquets | RedHeart", description: "Honour the women in your life with fresh flowers this Women's Day. Beautiful bouquets with same-day delivery across India. Order Women's Day flowers at RedHeart!" },
  'flowers/womens-day':                 { title: "Women's Day Flowers | Fresh Bouquets | RedHeart", description: "Honour the women in your life with fresh flowers this Women's Day. Beautiful bouquets with same-day delivery across India. Order Women's Day flowers at RedHeart!" },
  'florist-near-me/christmas':          { title: 'Christmas Flowers | Festive Bouquets | RedHeart', description: 'Celebrate Christmas with beautiful festive flower arrangements. Fresh poinsettias, lilies & winter bouquets with same-day delivery. Order Christmas flowers at RedHeart!' },
  'flowers/christmas':                  { title: 'Christmas Flowers | Festive Bouquets | RedHeart', description: 'Celebrate Christmas with beautiful festive flower arrangements. Fresh poinsettias, lilies & winter bouquets with same-day delivery. Order Christmas flowers at RedHeart!' },
  'florist-near-me/new-year':           { title: 'New Year Flowers | Fresh Bouquets Online | RedHeart', description: 'Ring in the New Year with stunning fresh flower bouquets. Bright, festive arrangements with same-day delivery across India. Order New Year flowers at RedHeart!' },
  'flowers/new-year':                   { title: 'New Year Flowers | Fresh Bouquets Online | RedHeart', description: 'Ring in the New Year with stunning fresh flower bouquets. Bright, festive arrangements with same-day delivery across India. Order New Year flowers at RedHeart!' },
  'florist-near-me/holi':               { title: 'Holi Flowers | Colourful Bouquets Online | RedHeart', description: 'Celebrate Holi with bright, colourful fresh flower bouquets. Festive floral arrangements with same-day delivery across India. Order Holi flowers at RedHeart!' },
  'flowers/holi':                       { title: 'Holi Flowers | Colourful Bouquets Online | RedHeart', description: 'Celebrate Holi with bright, colourful fresh flower bouquets. Festive floral arrangements with same-day delivery across India. Order Holi flowers at RedHeart!' },
  'florist-near-me/eid-al-fitr':        { title: 'Eid Flowers | Fresh Bouquets for Eid | RedHeart', description: 'Celebrate Eid Al Fitr with beautiful fresh flowers. Elegant bouquets & floral arrangements with same-day delivery. Order Eid flowers at RedHeart!' },
  'flowers/eid-al-fitr':                { title: 'Eid Flowers | Fresh Bouquets for Eid | RedHeart', description: 'Celebrate Eid Al Fitr with beautiful fresh flowers. Elegant bouquets & floral arrangements with same-day delivery. Order Eid flowers at RedHeart!' },
  'florist-near-me/fathers-day':        { title: "Father's Day Flowers | Fresh Bouquets | RedHeart", description: "Make Father's Day special with fresh flowers. Premium bouquets & arrangements with same-day delivery across India. Order Father's Day flowers at RedHeart!" },
  'flowers/fathers-day':                { title: "Father's Day Flowers | Fresh Bouquets | RedHeart", description: "Make Father's Day special with fresh flowers. Premium bouquets & arrangements with same-day delivery across India. Order Father's Day flowers at RedHeart!" },
  'florist-near-me/lohri':              { title: 'Lohri Flowers | Festive Bouquets Online | RedHeart', description: 'Celebrate Lohri with vibrant fresh flower bouquets. Bright, festive arrangements with same-day delivery across India. Order Lohri flowers at RedHeart!' },
  'flowers/lohri':                      { title: 'Lohri Flowers | Festive Bouquets Online | RedHeart', description: 'Celebrate Lohri with vibrant fresh flower bouquets. Bright, festive arrangements with same-day delivery across India. Order Lohri flowers at RedHeart!' },
  // Flower Popular
  'florist-near-me/red-roses':          { title: 'Red Roses Online | Same Day Delivery | RedHeart', description: 'Buy fresh red roses online — bouquets, bunches & heart arrangements. Same-day & midnight delivery across India from ₹399. Order red roses at RedHeart!' },
  'flowers/red-roses':                  { title: 'Red Roses Online | Same Day Delivery | RedHeart', description: 'Buy fresh red roses online — bouquets, bunches & heart arrangements. Same-day & midnight delivery across India from ₹399. Order red roses at RedHeart!' },
  'florist-near-me/pink-roses':         { title: 'Pink Roses Online | Fresh Pink Bouquets | RedHeart', description: 'Buy fresh pink roses online — soft, romantic pink rose bouquets with same-day delivery. Perfect for birthdays & anniversaries from ₹399. Order at RedHeart!' },
  'flowers/pink-roses':                 { title: 'Pink Roses Online | Fresh Pink Bouquets | RedHeart', description: 'Buy fresh pink roses online — soft, romantic pink rose bouquets with same-day delivery. Perfect for birthdays & anniversaries from ₹399. Order at RedHeart!' },
  'florist-near-me/white-lilies':       { title: 'White Lilies Online | Fresh Lily Bouquets | RedHeart', description: 'Buy fresh white lilies online — elegant bouquets & arrangements with same-day delivery across India. Pure, serene white lilies from ₹449. Order at RedHeart!' },
  'flowers/white-lilies':               { title: 'White Lilies Online | Fresh Lily Bouquets | RedHeart', description: 'Buy fresh white lilies online — elegant bouquets & arrangements with same-day delivery across India. Pure, serene white lilies from ₹449. Order at RedHeart!' },
  'florist-near-me/birthday-roses':     { title: 'Birthday Roses | Fresh Rose Bouquets | RedHeart', description: 'Surprise them on their birthday with fresh roses — red, pink & mixed rose birthday bouquets. Same-day & midnight delivery from ₹399. Order at RedHeart!' },
  'flowers/birthday-roses':             { title: 'Birthday Roses | Fresh Rose Bouquets | RedHeart', description: 'Surprise them on their birthday with fresh roses — red, pink & mixed rose birthday bouquets. Same-day & midnight delivery from ₹399. Order at RedHeart!' },
  'florist-near-me/anniversary-roses':  { title: 'Anniversary Roses | Romantic Bouquets | RedHeart', description: 'Celebrate your anniversary with fresh roses — romantic red & pink rose bouquets. Same-day & midnight delivery across India. Order anniversary roses at RedHeart!' },
  'flowers/anniversary-roses':          { title: 'Anniversary Roses | Romantic Bouquets | RedHeart', description: 'Celebrate your anniversary with fresh roses — romantic red & pink rose bouquets. Same-day & midnight delivery across India. Order anniversary roses at RedHeart!' },

  // ── CAKES ──────────────────────────────────────────────────────────────────
  'order-cake-online': {
    title:       'Order Cakes Online | Same Day Cake Delivery | RedHeart',
    description: 'Order fresh custom cakes online with same-day & midnight delivery. Birthday, anniversary & designer cakes starting ₹499. Up to 20% off. Shop at RedHeart!',
  },
  'cakes': {
    title:       'Order Cakes Online | Same Day Cake Delivery | RedHeart',
    description: 'Buy cakes online from RedHeart — fresh, delicious cakes delivered same-day. Birthday, anniversary, photo cakes & more from ₹499. Order now!',
  },
  'order-cake-online/hot-picks':        { title: 'Hot Pick Cakes Online | Trending Cakes | RedHeart', description: 'Order our most trending cakes online — hot-pick birthday, anniversary & designer cakes with same-day delivery from ₹499. Shop hot picks at RedHeart!' },
  'cakes/hot-picks':                    { title: 'Hot Pick Cakes Online | Trending Cakes | RedHeart', description: 'Order our most trending cakes online — hot-pick birthday, anniversary & designer cakes with same-day delivery from ₹499. Shop hot picks at RedHeart!' },
  'order-cake-online/best-sellers':     { title: 'Best Selling Cakes Online | Top Picks | RedHeart', description: 'Order our best-selling cakes loved by thousands — chocolate, red velvet, black forest & more with same-day delivery. Shop best sellers at RedHeart!' },
  'cakes/best-sellers':                 { title: 'Best Selling Cakes Online | Top Picks | RedHeart', description: 'Order our best-selling cakes loved by thousands — chocolate, red velvet, black forest & more with same-day delivery. Shop best sellers at RedHeart!' },
  'order-cake-online/new-arrivals':     { title: 'New Arrival Cakes Online | Latest Designs | RedHeart', description: 'Explore the latest cake designs at RedHeart — fresh new arrivals delivered same-day. Unique designer & custom cakes from ₹499. Order new arrival cakes now!' },
  'cakes/new-arrivals':                 { title: 'New Arrival Cakes Online | Latest Designs | RedHeart', description: 'Explore the latest cake designs at RedHeart — fresh new arrivals delivered same-day. Unique designer & custom cakes from ₹499. Order new arrival cakes now!' },
  // Flavours
  'order-cake-online/black-forest':     { title: 'Order Black Forest Cake Online | RedHeart', description: 'Order fresh Black Forest cakes online — classic chocolate sponge with cherries. Same-day & midnight delivery from ₹549. Eggless options available. Order at RedHeart!' },
  'cakes/black-forest':                 { title: 'Order Black Forest Cake Online | RedHeart', description: 'Order fresh Black Forest cakes online — classic chocolate sponge with cherries. Same-day & midnight delivery from ₹549. Eggless options available. Order at RedHeart!' },
  'order-cake-online/chocolate':        { title: 'Order Chocolate Cake Online | Same Day | RedHeart', description: 'Order rich chocolate cakes online — dark chocolate truffle, ganache & fudge cakes. Same-day delivery from ₹499. Eggless available. Buy chocolate cake at RedHeart!' },
  'cakes/chocolate':                    { title: 'Order Chocolate Cake Online | Same Day | RedHeart', description: 'Order rich chocolate cakes online — dark chocolate truffle, ganache & fudge cakes. Same-day delivery from ₹499. Eggless available. Buy chocolate cake at RedHeart!' },
  'order-cake-online/red-velvet':       { title: 'Order Red Velvet Cake Online | RedHeart', description: 'Order fresh red velvet cakes online — classic red velvet with cream cheese frosting. Same-day delivery from ₹549. Eggless options available. Buy at RedHeart!' },
  'cakes/red-velvet':                   { title: 'Order Red Velvet Cake Online | RedHeart', description: 'Order fresh red velvet cakes online — classic red velvet with cream cheese frosting. Same-day delivery from ₹549. Eggless options available. Buy at RedHeart!' },
  'order-cake-online/ferrero-rocher':   { title: 'Ferrero Rocher Cake Online | RedHeart', description: 'Order premium Ferrero Rocher cakes online — rich chocolate hazelnut cakes with same-day delivery. A luxurious treat from ₹699. Order Ferrero cake at RedHeart!' },
  'cakes/ferrero-rocher':               { title: 'Ferrero Rocher Cake Online | RedHeart', description: 'Order premium Ferrero Rocher cakes online — rich chocolate hazelnut cakes with same-day delivery. A luxurious treat from ₹699. Order Ferrero cake at RedHeart!' },
  'order-cake-online/pinata':           { title: 'Pinata Cake Online | Order Pinata Cakes | RedHeart', description: 'Order fun pinata cakes online — surprise-filled cakes perfect for birthdays. Same-day delivery from ₹799. Custom designs available. Order pinata cake at RedHeart!' },
  'cakes/pinata':                       { title: 'Pinata Cake Online | Order Pinata Cakes | RedHeart', description: 'Order fun pinata cakes online — surprise-filled cakes perfect for birthdays. Same-day delivery from ₹799. Custom designs available. Order pinata cake at RedHeart!' },
  // Cake Occasions
  'order-cake-online/birthday':         { title: 'Order Birthday Cakes Online | Same Day | RedHeart', description: 'Order fresh birthday cakes online — custom, photo & designer birthday cakes. Same-day & midnight delivery from ₹499. Eggless available. Order at RedHeart!' },
  'cakes/birthday':                     { title: 'Order Birthday Cakes Online | Same Day | RedHeart', description: 'Order fresh birthday cakes online — custom, photo & designer birthday cakes. Same-day & midnight delivery from ₹499. Eggless available. Order at RedHeart!' },
  'order-cake-online/anniversary':      { title: 'Anniversary Cakes Online | Order Now | RedHeart', description: 'Celebrate with a beautiful anniversary cake — custom & designer anniversary cakes. Same-day & midnight delivery from ₹549. Order anniversary cakes at RedHeart!' },
  'cakes/anniversary':                  { title: 'Anniversary Cakes Online | Order Now | RedHeart', description: 'Celebrate with a beautiful anniversary cake — custom & designer anniversary cakes. Same-day & midnight delivery from ₹549. Order anniversary cakes at RedHeart!' },
  'order-cake-online/wedding':          { title: 'Wedding Cakes Online | Custom Designs | RedHeart', description: 'Order stunning wedding cakes — multi-tier, fondant & floral designs. Custom wedding cake delivery across India. Order your dream wedding cake at RedHeart!' },
  'cakes/wedding':                      { title: 'Wedding Cakes Online | Custom Designs | RedHeart', description: 'Order stunning wedding cakes — multi-tier, fondant & floral designs. Custom wedding cake delivery across India. Order your dream wedding cake at RedHeart!' },
  'order-cake-online/valentine':        { title: "Valentine's Day Cakes Online | RedHeart", description: "Order romantic Valentine's Day cakes — heart-shaped, red velvet & chocolate cakes. Same-day & midnight delivery. Order Valentine cakes at RedHeart from ₹549!" },
  'cakes/valentine':                    { title: "Valentine's Day Cakes Online | RedHeart", description: "Order romantic Valentine's Day cakes — heart-shaped, red velvet & chocolate cakes. Same-day & midnight delivery. Order Valentine cakes at RedHeart from ₹549!" },
  'order-cake-online/congratulations':  { title: 'Congratulations Cakes Online | RedHeart', description: 'Order congratulations cakes online — customised celebration cakes for achievements. Same-day delivery from ₹499. Make it special with RedHeart cakes!' },
  'cakes/congratulations':              { title: 'Congratulations Cakes Online | RedHeart', description: 'Order congratulations cakes online — customised celebration cakes for achievements. Same-day delivery from ₹499. Make it special with RedHeart cakes!' },
  'order-cake-online/get-well-soon':    { title: 'Get Well Soon Cakes Online | RedHeart', description: 'Send a cheerful get well soon cake — sweet, thoughtful cakes with same-day delivery. A delicious way to lift spirits from ₹499. Order at RedHeart!' },
  'cakes/get-well-soon':                { title: 'Get Well Soon Cakes Online | RedHeart', description: 'Send a cheerful get well soon cake — sweet, thoughtful cakes with same-day delivery. A delicious way to lift spirits from ₹499. Order at RedHeart!' },
  'order-cake-online/thank-you':        { title: 'Thank You Cakes Online | Order Now | RedHeart', description: 'Say thank you with a delicious fresh cake. Customised thank you cakes with same-day delivery from ₹499. A sweet gesture delivered by RedHeart!' },
  'cakes/thank-you':                    { title: 'Thank You Cakes Online | Order Now | RedHeart', description: 'Say thank you with a delicious fresh cake. Customised thank you cakes with same-day delivery from ₹499. A sweet gesture delivered by RedHeart!' },
  'order-cake-online/house-warming':    { title: 'House Warming Cakes Online | RedHeart', description: 'Celebrate a new home with a special house warming cake. Custom cakes with same-day delivery from ₹499. Sweet beginnings with RedHeart!' },
  'cakes/house-warming':                { title: 'House Warming Cakes Online | RedHeart', description: 'Celebrate a new home with a special house warming cake. Custom cakes with same-day delivery from ₹499. Sweet beginnings with RedHeart!' },
  'order-cake-online/baby-shower':      { title: 'Baby Shower Cakes Online | Order Now | RedHeart', description: 'Order beautiful baby shower cakes — gender reveal, fondant & custom baby cakes. Same-day delivery from ₹549. Order baby shower cakes at RedHeart!' },
  'cakes/baby-shower':                  { title: 'Baby Shower Cakes Online | Order Now | RedHeart', description: 'Order beautiful baby shower cakes — gender reveal, fondant & custom baby cakes. Same-day delivery from ₹549. Order baby shower cakes at RedHeart!' },
  'order-cake-online/new-born-baby':    { title: 'New Born Baby Cakes Online | RedHeart', description: 'Welcome the newborn with a sweet fresh cake. Soft, elegant baby cakes with same-day delivery from ₹549. Celebrate new life with RedHeart cakes!' },
  'cakes/new-born-baby':                { title: 'New Born Baby Cakes Online | RedHeart', description: 'Welcome the newborn with a sweet fresh cake. Soft, elegant baby cakes with same-day delivery from ₹549. Celebrate new life with RedHeart cakes!' },
  'order-cake-online/appreciation':     { title: 'Appreciation Cakes Online | Order Now | RedHeart', description: 'Order appreciation cakes online — custom sweet gestures for colleagues, mentors & loved ones. Same-day delivery from ₹499. Order at RedHeart!' },
  'cakes/appreciation':                 { title: 'Appreciation Cakes Online | Order Now | RedHeart', description: 'Order appreciation cakes online — custom sweet gestures for colleagues, mentors & loved ones. Same-day delivery from ₹499. Order at RedHeart!' },
  'order-cake-online/cheer-up':         { title: 'Cheer Up Cakes Online | Sweet Surprises | RedHeart', description: 'Send a cheer up cake — bright, cheerful cakes to lift someone\'s spirits. Same-day delivery from ₹499. Sweet hugs delivered by RedHeart!' },
  'cakes/cheer-up':                     { title: 'Cheer Up Cakes Online | Sweet Surprises | RedHeart', description: 'Send a cheer up cake — bright, cheerful cakes to lift someone\'s spirits. Same-day delivery from ₹499. Sweet hugs delivered by RedHeart!' },
  'order-cake-online/i-am-sorry':       { title: 'Sorry Cakes Online | Sweet Apologies | RedHeart', description: 'Say sorry with a sweet fresh cake. Custom I Am Sorry cakes with same-day delivery from ₹499. A delicious apology delivered by RedHeart!' },
  'cakes/i-am-sorry':                   { title: 'Sorry Cakes Online | Sweet Apologies | RedHeart', description: 'Say sorry with a sweet fresh cake. Custom I Am Sorry cakes with same-day delivery from ₹499. A delicious apology delivered by RedHeart!' },
  // Cake Relationships
  'order-cake-online/for-her':          { title: 'Cakes for Her | Order Online | RedHeart', description: 'Order beautiful cakes for her — custom, floral & photo cakes for wife, girlfriend, mother & sister. Same-day delivery from ₹499. Order at RedHeart!' },
  'cakes/for-her':                      { title: 'Cakes for Her | Order Online | RedHeart', description: 'Order beautiful cakes for her — custom, floral & photo cakes for wife, girlfriend, mother & sister. Same-day delivery from ₹499. Order at RedHeart!' },
  'order-cake-online/for-him':          { title: 'Cakes for Him | Order Online | RedHeart', description: 'Order great cakes for him — chocolate, black forest & designer cakes for husband, boyfriend & dad. Same-day delivery from ₹499. Order at RedHeart!' },
  'cakes/for-him':                      { title: 'Cakes for Him | Order Online | RedHeart', description: 'Order great cakes for him — chocolate, black forest & designer cakes for husband, boyfriend & dad. Same-day delivery from ₹499. Order at RedHeart!' },
  'order-cake-online/for-wife':         { title: 'Cakes for Wife | Romantic Cake Delivery | RedHeart', description: 'Surprise your wife with a stunning cake — red velvet, floral & photo cakes with midnight delivery. Show your love with RedHeart from ₹549!' },
  'cakes/for-wife':                     { title: 'Cakes for Wife | Romantic Cake Delivery | RedHeart', description: 'Surprise your wife with a stunning cake — red velvet, floral & photo cakes with midnight delivery. Show your love with RedHeart from ₹549!' },
  'order-cake-online/for-husband':      { title: 'Cakes for Husband | Order Online | RedHeart', description: 'Order a special cake for your husband — chocolate, customised & designer cakes with same-day & midnight delivery. Order cakes for husband at RedHeart!' },
  'cakes/for-husband':                  { title: 'Cakes for Husband | Order Online | RedHeart', description: 'Order a special cake for your husband — chocolate, customised & designer cakes with same-day & midnight delivery. Order cakes for husband at RedHeart!' },
  'order-cake-online/for-mother':       { title: 'Cakes for Mother | Fresh Cakes Online | RedHeart', description: 'Order a beautiful cake for your mother — fresh, custom cakes with same-day delivery. Celebrate mum with something sweet from RedHeart from ₹499!' },
  'cakes/for-mother':                   { title: 'Cakes for Mother | Fresh Cakes Online | RedHeart', description: 'Order a beautiful cake for your mother — fresh, custom cakes with same-day delivery. Celebrate mum with something sweet from RedHeart from ₹499!' },
  'order-cake-online/for-father':       { title: 'Cakes for Father | Order Online | RedHeart', description: 'Get a special cake for dad — chocolate, classic & custom cakes with same-day delivery from ₹499. Surprise your father with RedHeart!' },
  'cakes/for-father':                   { title: 'Cakes for Father | Order Online | RedHeart', description: 'Get a special cake for dad — chocolate, classic & custom cakes with same-day delivery from ₹499. Surprise your father with RedHeart!' },
  'order-cake-online/for-girlfriend':   { title: 'Cakes for Girlfriend | Romantic Cakes | RedHeart', description: 'Order a romantic cake for your girlfriend — heart, floral & photo cakes. Same-day & midnight delivery from ₹499. Impress her with RedHeart cakes!' },
  'cakes/for-girlfriend':               { title: 'Cakes for Girlfriend | Romantic Cakes | RedHeart', description: 'Order a romantic cake for your girlfriend — heart, floral & photo cakes. Same-day & midnight delivery from ₹499. Impress her with RedHeart cakes!' },
  'order-cake-online/for-boyfriend':    { title: 'Cakes for Boyfriend | Order Online | RedHeart', description: 'Surprise your boyfriend with a delicious cake — chocolate, custom & themed cakes. Same-day & midnight delivery from ₹499. Order at RedHeart!' },
  'cakes/for-boyfriend':                { title: 'Cakes for Boyfriend | Order Online | RedHeart', description: 'Surprise your boyfriend with a delicious cake — chocolate, custom & themed cakes. Same-day & midnight delivery from ₹499. Order at RedHeart!' },
  'order-cake-online/for-friends':      { title: 'Cakes for Friends | Fun Cakes Online | RedHeart', description: 'Order fun cakes for friends — custom, themed & photo cakes for friend groups. Same-day delivery from ₹499. Celebrate friendship with RedHeart!' },
  'cakes/for-friends':                  { title: 'Cakes for Friends | Fun Cakes Online | RedHeart', description: 'Order fun cakes for friends — custom, themed & photo cakes for friend groups. Same-day delivery from ₹499. Celebrate friendship with RedHeart!' },
  'order-cake-online/for-kids':         { title: 'Kids Cakes Online | Fun Themed Cakes | RedHeart', description: 'Order fun, cartoon & themed cakes for kids — colourful birthday cakes with same-day delivery. Eggless options available from ₹499. Order at RedHeart!' },
  'cakes/for-kids':                     { title: 'Kids Cakes Online | Fun Themed Cakes | RedHeart', description: 'Order fun, cartoon & themed cakes for kids — colourful birthday cakes with same-day delivery. Eggless options available from ₹499. Order at RedHeart!' },
  'order-cake-online/for-brother':      { title: 'Cakes for Brother | Order Online | RedHeart', description: 'Get a special cake for your brother — chocolate, custom & themed cakes with same-day delivery from ₹499. Celebrate bro with RedHeart!' },
  'cakes/for-brother':                  { title: 'Cakes for Brother | Order Online | RedHeart', description: 'Get a special cake for your brother — chocolate, custom & themed cakes with same-day delivery from ₹499. Celebrate bro with RedHeart!' },
  'order-cake-online/for-sister':       { title: 'Cakes for Sister | Order Online | RedHeart', description: 'Order a beautiful cake for your sister — floral, photo & custom cakes with same-day delivery from ₹499. Sweet surprises by RedHeart!' },
  'cakes/for-sister':                   { title: 'Cakes for Sister | Order Online | RedHeart', description: 'Order a beautiful cake for your sister — floral, photo & custom cakes with same-day delivery from ₹499. Sweet surprises by RedHeart!' },
  // Cake Festivals
  'order-cake-online/valentines-day':   { title: "Order Valentine's Day Cakes | RedHeart", description: "Order romantic Valentine's Day cakes — heart, red velvet & chocolate cakes. Same-day & midnight delivery from ₹549. Sweeten Valentine's Day with RedHeart!" },
  'cakes/valentines-day':               { title: "Order Valentine's Day Cakes | RedHeart", description: "Order romantic Valentine's Day cakes — heart, red velvet & chocolate cakes. Same-day & midnight delivery from ₹549. Sweeten Valentine's Day with RedHeart!" },
  'order-cake-online/mothers-day':      { title: "Mother's Day Cakes Online | RedHeart", description: "Order a special Mother's Day cake — floral, custom & elegant cakes with same-day delivery. Celebrate mum sweetly from ₹549. Order at RedHeart!" },
  'cakes/mothers-day':                  { title: "Mother's Day Cakes Online | RedHeart", description: "Order a special Mother's Day cake — floral, custom & elegant cakes with same-day delivery. Celebrate mum sweetly from ₹549. Order at RedHeart!" },
  'order-cake-online/christmas':        { title: 'Christmas Cakes Online | Order Now | RedHeart', description: 'Order festive Christmas cakes — plum, chocolate & themed Xmas cakes with same-day delivery. Sweet Christmas celebrations from ₹549. Order at RedHeart!' },
  'cakes/christmas':                    { title: 'Christmas Cakes Online | Order Now | RedHeart', description: 'Order festive Christmas cakes — plum, chocolate & themed Xmas cakes with same-day delivery. Sweet Christmas celebrations from ₹549. Order at RedHeart!' },
  'order-cake-online/new-year':         { title: 'New Year Cakes Online | Order Now | RedHeart', description: 'Celebrate the New Year with a fresh cake. Custom, themed & designer New Year cakes with same-day delivery from ₹499. Order New Year cakes at RedHeart!' },
  'cakes/new-year':                     { title: 'New Year Cakes Online | Order Now | RedHeart', description: 'Celebrate the New Year with a fresh cake. Custom, themed & designer New Year cakes with same-day delivery from ₹499. Order New Year cakes at RedHeart!' },
  'order-cake-online/womens-day':       { title: "Women's Day Cakes Online | RedHeart", description: "Celebrate Women's Day with a stunning cake. Custom & floral Women's Day cakes with same-day delivery from ₹499. Order Women's Day cakes at RedHeart!" },
  'cakes/womens-day':                   { title: "Women's Day Cakes Online | RedHeart", description: "Celebrate Women's Day with a stunning cake. Custom & floral Women's Day cakes with same-day delivery from ₹499. Order Women's Day cakes at RedHeart!" },
  'order-cake-online/eid-al-fitr':      { title: 'Eid Cakes Online | Order Eid Cakes | RedHeart', description: 'Celebrate Eid Al Fitr with a beautiful fresh cake. Traditional & designer Eid cakes with same-day delivery from ₹499. Order Eid cakes at RedHeart!' },
  'cakes/eid-al-fitr':                  { title: 'Eid Cakes Online | Order Eid Cakes | RedHeart', description: 'Celebrate Eid Al Fitr with a beautiful fresh cake. Traditional & designer Eid cakes with same-day delivery from ₹499. Order Eid cakes at RedHeart!' },
  'order-cake-online/fathers-day':      { title: "Father's Day Cakes Online | RedHeart", description: "Surprise dad with a special Father's Day cake — chocolate, custom & designer cakes with same-day delivery from ₹499. Order Father's Day cakes at RedHeart!" },
  'cakes/fathers-day':                  { title: "Father's Day Cakes Online | RedHeart", description: "Surprise dad with a special Father's Day cake — chocolate, custom & designer cakes with same-day delivery from ₹499. Order Father's Day cakes at RedHeart!" },
  'order-cake-online/holi':             { title: 'Holi Cakes Online | Colourful Cakes | RedHeart', description: 'Celebrate Holi with a vibrant, colourful fresh cake. Fun Holi-themed cakes with same-day delivery from ₹499. Order Holi cakes at RedHeart!' },
  'cakes/holi':                         { title: 'Holi Cakes Online | Colourful Cakes | RedHeart', description: 'Celebrate Holi with a vibrant, colourful fresh cake. Fun Holi-themed cakes with same-day delivery from ₹499. Order Holi cakes at RedHeart!' },
  // Cake Popular Combos
  'order-cake-online/birthday-chocolate':    { title: 'Birthday Chocolate Cake Online | RedHeart', description: 'Order a rich birthday chocolate cake — truffle, ganache & fudge birthday cakes. Same-day & midnight delivery from ₹549. Eggless available. Order at RedHeart!' },
  'cakes/birthday-chocolate':                { title: 'Birthday Chocolate Cake Online | RedHeart', description: 'Order a rich birthday chocolate cake — truffle, ganache & fudge birthday cakes. Same-day & midnight delivery from ₹549. Eggless available. Order at RedHeart!' },
  'order-cake-online/birthday-black-forest': { title: 'Birthday Black Forest Cake Online | RedHeart', description: 'Order a classic birthday black forest cake — rich chocolate with cherry topping. Same-day & midnight delivery from ₹549. Eggless available. Order at RedHeart!' },
  'cakes/birthday-black-forest':             { title: 'Birthday Black Forest Cake Online | RedHeart', description: 'Order a classic birthday black forest cake — rich chocolate with cherry topping. Same-day & midnight delivery from ₹549. Eggless available. Order at RedHeart!' },
  'order-cake-online/anniversary-red-velvet':{ title: 'Anniversary Red Velvet Cake Online | RedHeart', description: 'Celebrate your anniversary with a fresh red velvet cake — romantic red velvet with cream cheese. Same-day & midnight delivery from ₹599. Order at RedHeart!' },
  'cakes/anniversary-red-velvet':            { title: 'Anniversary Red Velvet Cake Online | RedHeart', description: 'Celebrate your anniversary with a fresh red velvet cake — romantic red velvet with cream cheese. Same-day & midnight delivery from ₹599. Order at RedHeart!' },

  // ── PLANTS ─────────────────────────────────────────────────────────────────
  'plants-online': {
    title:       'Buy Plants Online | Same Day Plant Delivery | RedHeart',
    description: 'Order indoor, outdoor & flowering plants online with same-day delivery. Succulents, air-purifying & lucky plants from ₹299. Free shipping on select orders. Shop RedHeart!',
  },
  'plants': {
    title:       'Buy Plants Online | Same Day Plant Delivery | RedHeart',
    description: 'Buy plants online in India — indoor, outdoor, succulents & gift plants with same-day delivery from ₹299. Healthy, well-rooted plants at RedHeart!',
  },
  'plants-online/hot-picks':            { title: 'Hot Pick Plants Online | Trending Plants | RedHeart', description: 'Discover our most popular plants — trending succulents, indoor & lucky plants with same-day delivery from ₹299. Shop hot-pick plants at RedHeart!' },
  'plants/hot-picks':                   { title: 'Hot Pick Plants Online | Trending Plants | RedHeart', description: 'Discover our most popular plants — trending succulents, indoor & lucky plants with same-day delivery from ₹299. Shop hot-pick plants at RedHeart!' },
  'plants-online/best-sellers':         { title: 'Best Selling Plants Online | Top Picks | RedHeart', description: 'Shop our best-selling plants — loved by thousands of happy customers. Indoor & outdoor plants with same-day delivery from ₹299. Order at RedHeart!' },
  'plants/best-sellers':                { title: 'Best Selling Plants Online | Top Picks | RedHeart', description: 'Shop our best-selling plants — loved by thousands of happy customers. Indoor & outdoor plants with same-day delivery from ₹299. Order at RedHeart!' },
  'plants-online/new-arrivals':         { title: 'New Arrival Plants Online | Latest Plants | RedHeart', description: 'Explore the latest plant arrivals — fresh new varieties delivered same-day. Unique indoor & outdoor plants from ₹299. Shop new arrivals at RedHeart!' },
  'plants/new-arrivals':                { title: 'New Arrival Plants Online | Latest Plants | RedHeart', description: 'Explore the latest plant arrivals — fresh new varieties delivered same-day. Unique indoor & outdoor plants from ₹299. Shop new arrivals at RedHeart!' },
  // Varieties
  'plants-online/snake':                { title: 'Buy Snake Plant Online | Indoor Plants | RedHeart', description: 'Buy fresh snake plants online — low-maintenance air-purifying indoor plants. Same-day delivery from ₹299. Perfect for homes & offices. Order at RedHeart!' },
  'plants/snake':                       { title: 'Buy Snake Plant Online | Indoor Plants | RedHeart', description: 'Buy fresh snake plants online — low-maintenance air-purifying indoor plants. Same-day delivery from ₹299. Perfect for homes & offices. Order at RedHeart!' },
  'plants-online/money':                { title: 'Buy Money Plant Online | Lucky Plants | RedHeart', description: 'Buy fresh money plants online — a lucky Vastu-friendly indoor plant. Same-day delivery from ₹199. Perfect gift for homes & offices. Order at RedHeart!' },
  'plants/money':                       { title: 'Buy Money Plant Online | Lucky Plants | RedHeart', description: 'Buy fresh money plants online — a lucky Vastu-friendly indoor plant. Same-day delivery from ₹199. Perfect gift for homes & offices. Order at RedHeart!' },
  'plants-online/jade':                 { title: 'Buy Jade Plant Online | Lucky Plant | RedHeart', description: 'Buy fresh jade plants online — a symbol of good luck & prosperity. Low-maintenance succulent with same-day delivery from ₹249. Order at RedHeart!' },
  'plants/jade':                        { title: 'Buy Jade Plant Online | Lucky Plant | RedHeart', description: 'Buy fresh jade plants online — a symbol of good luck & prosperity. Low-maintenance succulent with same-day delivery from ₹249. Order at RedHeart!' },
  'plants-online/peace-lily':           { title: 'Buy Peace Lily Plant Online | RedHeart', description: 'Buy fresh peace lily plants online — elegant air-purifying indoor plants. Same-day delivery from ₹299. Perfect for homes, offices & gifting. Order at RedHeart!' },
  'plants/peace-lily':                  { title: 'Buy Peace Lily Plant Online | RedHeart', description: 'Buy fresh peace lily plants online — elegant air-purifying indoor plants. Same-day delivery from ₹299. Perfect for homes, offices & gifting. Order at RedHeart!' },
  'plants-online/syngonium':            { title: 'Buy Syngonium Plant Online | RedHeart', description: 'Buy fresh syngonium plants online — beautiful arrow-head foliage plants. Low-maintenance & air-purifying with same-day delivery from ₹249. Order at RedHeart!' },
  'plants/syngonium':                   { title: 'Buy Syngonium Plant Online | RedHeart', description: 'Buy fresh syngonium plants online — beautiful arrow-head foliage plants. Low-maintenance & air-purifying with same-day delivery from ₹249. Order at RedHeart!' },
  'plants-online/bonsai':               { title: 'Buy Bonsai Plant Online | RedHeart', description: 'Buy fresh bonsai plants online — artistic miniature trees for homes & offices. Same-day delivery from ₹499. Unique living gifts. Order bonsai at RedHeart!' },
  'plants/bonsai':                      { title: 'Buy Bonsai Plant Online | RedHeart', description: 'Buy fresh bonsai plants online — artistic miniature trees for homes & offices. Same-day delivery from ₹499. Unique living gifts. Order bonsai at RedHeart!' },
  // Plants Occasions
  'plants-online/birthday':             { title: 'Birthday Plants Online | Green Gifts | RedHeart', description: 'Gift a plant on their birthday — long-lasting, eco-friendly birthday plants. Same-day delivery from ₹299. A gift that keeps growing. Order at RedHeart!' },
  'plants/birthday':                    { title: 'Birthday Plants Online | Green Gifts | RedHeart', description: 'Gift a plant on their birthday — long-lasting, eco-friendly birthday plants. Same-day delivery from ₹299. A gift that keeps growing. Order at RedHeart!' },
  'plants-online/anniversary':          { title: 'Anniversary Plants Online | Green Gifts | RedHeart', description: 'Celebrate your anniversary with a beautiful plant. Lasting green gifts with same-day delivery from ₹299. A living symbol of love. Order at RedHeart!' },
  'plants/anniversary':                 { title: 'Anniversary Plants Online | Green Gifts | RedHeart', description: 'Celebrate your anniversary with a beautiful plant. Lasting green gifts with same-day delivery from ₹299. A living symbol of love. Order at RedHeart!' },
  'plants-online/wedding':              { title: 'Wedding Plants Online | Green Decor | RedHeart', description: 'Beautiful wedding plants — bonsai, peace lily & money plants for weddings. Same-day delivery for your special day. Order wedding plants at RedHeart!' },
  'plants/wedding':                     { title: 'Wedding Plants Online | Green Decor | RedHeart', description: 'Beautiful wedding plants — bonsai, peace lily & money plants for weddings. Same-day delivery for your special day. Order wedding plants at RedHeart!' },
  'plants-online/house-warming':        { title: 'House Warming Plants | Vastu Plants | RedHeart', description: 'Gift a lucky Vastu plant for house warming — money plant, bamboo & peace lily with same-day delivery. Bring prosperity home. Order at RedHeart!' },
  'plants/house-warming':               { title: 'House Warming Plants | Vastu Plants | RedHeart', description: 'Gift a lucky Vastu plant for house warming — money plant, bamboo & peace lily with same-day delivery. Bring prosperity home. Order at RedHeart!' },
  'plants-online/congratulations':      { title: 'Congratulations Plants Online | RedHeart', description: 'Gift a plant to congratulate — beautiful indoor plants for achievements. Same-day delivery from ₹299. A green, lasting congratulations. Order at RedHeart!' },
  'plants/congratulations':             { title: 'Congratulations Plants Online | RedHeart', description: 'Gift a plant to congratulate — beautiful indoor plants for achievements. Same-day delivery from ₹299. A green, lasting congratulations. Order at RedHeart!' },
  'plants-online/get-well-soon':        { title: 'Get Well Soon Plants Online | RedHeart', description: 'Send a healing plant — air-purifying & calming plants for get well soon. Same-day delivery from ₹299. A green hug delivered by RedHeart!' },
  'plants/get-well-soon':               { title: 'Get Well Soon Plants Online | RedHeart', description: 'Send a healing plant — air-purifying & calming plants for get well soon. Same-day delivery from ₹299. A green hug delivered by RedHeart!' },
  'plants-online/thank-you':            { title: 'Thank You Plants Online | Green Gifts | RedHeart', description: 'Say thank you with a beautiful plant — long-lasting green gifts with same-day delivery from ₹299. A living thank you from RedHeart!' },
  'plants/thank-you':                   { title: 'Thank You Plants Online | Green Gifts | RedHeart', description: 'Say thank you with a beautiful plant — long-lasting green gifts with same-day delivery from ₹299. A living thank you from RedHeart!' },
  'plants-online/baby-shower':          { title: 'Baby Shower Plants Online | RedHeart', description: 'Celebrate new arrivals with a beautiful plant — soft, green baby shower plants. Same-day delivery from ₹299. A lasting gift for new parents. Order at RedHeart!' },
  'plants/baby-shower':                 { title: 'Baby Shower Plants Online | RedHeart', description: 'Celebrate new arrivals with a beautiful plant — soft, green baby shower plants. Same-day delivery from ₹299. A lasting gift for new parents. Order at RedHeart!' },
  'plants-online/new-born-baby':        { title: 'New Born Baby Plants | Green Gifts | RedHeart', description: 'Welcome a newborn with a beautiful plant. Soft, safe indoor plants for baby celebrations. Same-day delivery from ₹299. Order at RedHeart!' },
  'plants/new-born-baby':               { title: 'New Born Baby Plants | Green Gifts | RedHeart', description: 'Welcome a newborn with a beautiful plant. Soft, safe indoor plants for baby celebrations. Same-day delivery from ₹299. Order at RedHeart!' },
  'plants-online/appreciation':         { title: 'Appreciation Plants Online | RedHeart', description: 'Show appreciation with a beautiful plant — long-lasting green gifts for colleagues & mentors. Same-day delivery from ₹299. Order at RedHeart!' },
  'plants/appreciation':                { title: 'Appreciation Plants Online | RedHeart', description: 'Show appreciation with a beautiful plant — long-lasting green gifts for colleagues & mentors. Same-day delivery from ₹299. Order at RedHeart!' },
  'plants-online/love-and-romance':     { title: 'Love & Romance Plants Online | RedHeart', description: 'Gift a plant to express love — romantic living gifts for your special one. Same-day delivery from ₹299. A green symbol of love. Order at RedHeart!' },
  'plants/love-and-romance':            { title: 'Love & Romance Plants Online | RedHeart', description: 'Gift a plant to express love — romantic living gifts for your special one. Same-day delivery from ₹299. A green symbol of love. Order at RedHeart!' },
  'plants-online/cheer-up':             { title: 'Cheer Up Plants Online | Green Gifts | RedHeart', description: 'Send a cheerful plant to lift someone\'s spirits. Bright, beautiful plants delivered same-day from ₹299. A green smile from RedHeart!' },
  'plants/cheer-up':                    { title: 'Cheer Up Plants Online | Green Gifts | RedHeart', description: 'Send a cheerful plant to lift someone\'s spirits. Bright, beautiful plants delivered same-day from ₹299. A green smile from RedHeart!' },
  // Plants Relationships
  'plants-online/for-her':              { title: 'Plants for Her | Indoor Plants Online | RedHeart', description: 'Buy indoor plants for her — beautiful flowering & foliage plants for women. Same-day delivery from ₹299. A lasting green gift. Order at RedHeart!' },
  'plants/for-her':                     { title: 'Plants for Her | Indoor Plants Online | RedHeart', description: 'Buy indoor plants for her — beautiful flowering & foliage plants for women. Same-day delivery from ₹299. A lasting green gift. Order at RedHeart!' },
  'plants-online/for-him':              { title: 'Plants for Him | Indoor Plants Online | RedHeart', description: 'Buy plants for him — sturdy, low-maintenance indoor plants for men. Same-day delivery from ₹299. A green, lasting gift. Order at RedHeart!' },
  'plants/for-him':                     { title: 'Plants for Him | Indoor Plants Online | RedHeart', description: 'Buy plants for him — sturdy, low-maintenance indoor plants for men. Same-day delivery from ₹299. A green, lasting gift. Order at RedHeart!' },
  'plants-online/for-wife':             { title: 'Plants for Wife | Romantic Plant Gifts | RedHeart', description: 'Surprise your wife with a beautiful plant — elegant flowering & foliage plants. Same-day delivery from ₹299. A living gift of love. Order at RedHeart!' },
  'plants/for-wife':                    { title: 'Plants for Wife | Romantic Plant Gifts | RedHeart', description: 'Surprise your wife with a beautiful plant — elegant flowering & foliage plants. Same-day delivery from ₹299. A living gift of love. Order at RedHeart!' },
  'plants-online/for-husband':          { title: 'Plants for Husband | Online Plants | RedHeart', description: 'Gift your husband a beautiful plant — bonsai, succulents & lucky plants with same-day delivery from ₹299. A lasting green gift. Order at RedHeart!' },
  'plants/for-husband':                 { title: 'Plants for Husband | Online Plants | RedHeart', description: 'Gift your husband a beautiful plant — bonsai, succulents & lucky plants with same-day delivery from ₹299. A lasting green gift. Order at RedHeart!' },
  'plants-online/for-mother':           { title: 'Plants for Mother | Green Gifts | RedHeart', description: 'Gift your mother a beautiful plant — flowering, indoor & lucky plants with same-day delivery from ₹299. A living, lasting expression of love. Order at RedHeart!' },
  'plants/for-mother':                  { title: 'Plants for Mother | Green Gifts | RedHeart', description: 'Gift your mother a beautiful plant — flowering, indoor & lucky plants with same-day delivery from ₹299. A living, lasting expression of love. Order at RedHeart!' },
  'plants-online/for-father':           { title: 'Plants for Father | Green Gifts | RedHeart', description: 'Buy a plant for your father — bonsai, money plant & outdoor plants with same-day delivery from ₹299. A meaningful green gift. Order at RedHeart!' },
  'plants/for-father':                  { title: 'Plants for Father | Green Gifts | RedHeart', description: 'Buy a plant for your father — bonsai, money plant & outdoor plants with same-day delivery from ₹299. A meaningful green gift. Order at RedHeart!' },
  'plants-online/for-girlfriend':       { title: 'Plants for Girlfriend | Green Gifts | RedHeart', description: 'Gift your girlfriend a beautiful plant — romantic flowering & lucky plants with same-day delivery. A living, lasting gift from RedHeart from ₹299!' },
  'plants/for-girlfriend':              { title: 'Plants for Girlfriend | Green Gifts | RedHeart', description: 'Gift your girlfriend a beautiful plant — romantic flowering & lucky plants with same-day delivery. A living, lasting gift from RedHeart from ₹299!' },
  'plants-online/for-boyfriend':        { title: 'Plants for Boyfriend | Green Gifts | RedHeart', description: 'Gift your boyfriend a plant — cool, low-maintenance plants with same-day delivery from ₹299. A unique, lasting green gift. Order at RedHeart!' },
  'plants/for-boyfriend':               { title: 'Plants for Boyfriend | Green Gifts | RedHeart', description: 'Gift your boyfriend a plant — cool, low-maintenance plants with same-day delivery from ₹299. A unique, lasting green gift. Order at RedHeart!' },
  'plants-online/for-friends':          { title: 'Plants for Friends | Green Gifts Online | RedHeart', description: 'Send plants to your friends — cheerful indoor & lucky plants with same-day delivery from ₹299. A green, lasting friendship gift. Order at RedHeart!' },
  'plants/for-friends':                 { title: 'Plants for Friends | Green Gifts Online | RedHeart', description: 'Send plants to your friends — cheerful indoor & lucky plants with same-day delivery from ₹299. A green, lasting friendship gift. Order at RedHeart!' },
  'plants-online/for-kids':             { title: 'Plants for Kids | Fun Easy Plants | RedHeart', description: 'Buy fun, easy plants for kids — succulents, cactus & colourful flowering plants. Same-day delivery from ₹199. Grow a green habit. Order at RedHeart!' },
  'plants/for-kids':                    { title: 'Plants for Kids | Fun Easy Plants | RedHeart', description: 'Buy fun, easy plants for kids — succulents, cactus & colourful flowering plants. Same-day delivery from ₹199. Grow a green habit. Order at RedHeart!' },
  // Plants Festivals
  'plants-online/valentines-day':       { title: "Valentine's Day Plants Online | RedHeart", description: "Gift a plant this Valentine's Day — romantic flowering & lucky plants with same-day delivery. A love that grows from ₹299. Order Valentine plants at RedHeart!" },
  'plants/valentines-day':              { title: "Valentine's Day Plants Online | RedHeart", description: "Gift a plant this Valentine's Day — romantic flowering & lucky plants with same-day delivery. A love that grows from ₹299. Order Valentine plants at RedHeart!" },
  'plants-online/mothers-day':          { title: "Mother's Day Plants Online | RedHeart", description: "Celebrate Mother's Day with a beautiful plant — lasting green gifts with same-day delivery from ₹299. A living token of love. Order Mother's Day plants at RedHeart!" },
  'plants/mothers-day':                 { title: "Mother's Day Plants Online | RedHeart", description: "Celebrate Mother's Day with a beautiful plant — lasting green gifts with same-day delivery from ₹299. A living token of love. Order Mother's Day plants at RedHeart!" },
  'plants-online/womens-day':           { title: "Women's Day Plants Online | RedHeart", description: "Honour women with a beautiful plant this Women's Day. Elegant indoor & flowering plants with same-day delivery from ₹299. Order Women's Day plants at RedHeart!" },
  'plants/womens-day':                  { title: "Women's Day Plants Online | RedHeart", description: "Honour women with a beautiful plant this Women's Day. Elegant indoor & flowering plants with same-day delivery from ₹299. Order Women's Day plants at RedHeart!" },
  'plants-online/christmas':            { title: 'Christmas Plants Online | Festive Plants | RedHeart', description: 'Celebrate Christmas with festive plants — poinsettia, Christmas tree & green arrangements. Same-day delivery from ₹299. Order Christmas plants at RedHeart!' },
  'plants/christmas':                   { title: 'Christmas Plants Online | Festive Plants | RedHeart', description: 'Celebrate Christmas with festive plants — poinsettia, Christmas tree & green arrangements. Same-day delivery from ₹299. Order Christmas plants at RedHeart!' },
  'plants-online/new-year':             { title: 'New Year Plants Online | Green Gifts | RedHeart', description: 'Start the New Year with fresh plants. Lucky & indoor plants with same-day delivery from ₹299. A green start to the year. Order New Year plants at RedHeart!' },
  'plants/new-year':                    { title: 'New Year Plants Online | Green Gifts | RedHeart', description: 'Start the New Year with fresh plants. Lucky & indoor plants with same-day delivery from ₹299. A green start to the year. Order New Year plants at RedHeart!' },
  'plants-online/eid-al-fitr':          { title: 'Eid Plants Online | Green Gifts for Eid | RedHeart', description: 'Celebrate Eid with a beautiful plant — lucky & flowering plants as Eid gifts. Same-day delivery from ₹299. Green Eid blessings. Order at RedHeart!' },
  'plants/eid-al-fitr':                 { title: 'Eid Plants Online | Green Gifts for Eid | RedHeart', description: 'Celebrate Eid with a beautiful plant — lucky & flowering plants as Eid gifts. Same-day delivery from ₹299. Green Eid blessings. Order at RedHeart!' },
  'plants-online/fathers-day':          { title: "Father's Day Plants Online | RedHeart", description: "Gift dad a plant this Father's Day — bonsai, lucky & outdoor plants with same-day delivery from ₹299. A lasting green gift. Order Father's Day plants at RedHeart!" },
  'plants/fathers-day':                 { title: "Father's Day Plants Online | RedHeart", description: "Gift dad a plant this Father's Day — bonsai, lucky & outdoor plants with same-day delivery from ₹299. A lasting green gift. Order Father's Day plants at RedHeart!" },

  // ── BIRTHDAY ───────────────────────────────────────────────────────────────
  'birthday': {
    title:       'Birthday Gifts Online | Same Day Delivery | RedHeart',
    description: 'Order birthday gifts online — fresh flowers, custom cakes & plants. Same-day & midnight delivery across India from ₹399. Free birthday card. Shop RedHeart!',
  },
  'birthday-gifts-delivery': {
    title:       'Birthday Gifts Online | Same Day Delivery | RedHeart',
    description: 'Order birthday gifts online — fresh flowers, custom cakes & plants. Same-day & midnight delivery across India from ₹399. Free birthday card. Shop RedHeart!',
  },
  'birthday/flowers':          { title: 'Birthday Flowers | Same Day Delivery | RedHeart', description: 'Send birthday flowers — fresh roses, lilies & mixed bouquets. Same-day & midnight delivery from ₹399. Surprise them with blooms. Order at RedHeart!' },
  'birthday/cakes':            { title: 'Order Birthday Cakes Online | RedHeart', description: 'Order fresh birthday cakes — custom, photo & designer cakes. Same-day & midnight delivery from ₹499. Eggless options available. Order birthday cakes at RedHeart!' },
  'birthday/plants':           { title: 'Birthday Plants Online | Green Gifts | RedHeart', description: 'Gift a beautiful plant for their birthday — long-lasting green gifts with same-day delivery from ₹299. A birthday gift that keeps growing. Order at RedHeart!' },
  'birthday/gifts-for-her':    { title: 'Birthday Gifts for Her | Same Day | RedHeart', description: 'Order birthday gifts for her — flowers, cakes & plants with same-day delivery. Perfect for girlfriend, wife, mother & sister. Shop birthday gifts at RedHeart!' },
  'birthday/gifts-for-him':    { title: 'Birthday Gifts for Him | Same Day | RedHeart', description: 'Order birthday gifts for him — flowers, cakes & plants with same-day delivery. Perfect for boyfriend, husband & dad. Shop birthday gifts at RedHeart!' },
  'birthday/gifts-for-wife':   { title: 'Birthday Gifts for Wife | Same Day | RedHeart', description: 'Send birthday gifts to your wife — roses, cakes & plants with midnight delivery. Make her birthday extra special. Order birthday gifts for wife at RedHeart!' },
  'birthday/gifts-for-husband':{ title: 'Birthday Gifts for Husband | Same Day | RedHeart', description: 'Order birthday gifts for husband — flowers, cakes & plants. Same-day & midnight delivery across India. Surprise your husband with RedHeart!' },
  'birthday/gifts-for-mother': { title: 'Birthday Gifts for Mother | Same Day | RedHeart', description: 'Send birthday gifts to your mother — fresh flowers, cakes & plants. Same-day delivery across India. Make mum\'s birthday memorable with RedHeart!' },
  'birthday/gifts-for-father': { title: 'Birthday Gifts for Father | Same Day | RedHeart', description: 'Order birthday gifts for dad — flowers, cakes & plants with same-day delivery. Celebrate your father\'s birthday with love from RedHeart!' },
  'birthday/gifts-for-girlfriend': { title: 'Birthday Gifts for Girlfriend | RedHeart', description: 'Surprise your girlfriend with birthday gifts — roses, romantic cakes & plants. Midnight & same-day delivery. Order birthday gifts for girlfriend at RedHeart!' },
  'birthday/gifts-for-boyfriend': { title: 'Birthday Gifts for Boyfriend | RedHeart', description: 'Order birthday gifts for boyfriend — flowers, cakes & plants. Same-day & midnight delivery. Make his birthday unforgettable with RedHeart!' },
  'birthday/gifts-for-friends': { title: 'Birthday Gifts for Friends | Same Day | RedHeart', description: 'Send birthday gifts to your friends — flowers, cakes & plants with same-day delivery. Celebrate friendship with RedHeart from ₹399!' },
  'birthday/gifts-for-brother': { title: 'Birthday Gifts for Brother | Same Day | RedHeart', description: 'Order birthday gifts for your brother — flowers, cakes & plants with same-day delivery. Celebrate bro\'s birthday with RedHeart!' },
  'birthday/gifts-for-sister':  { title: 'Birthday Gifts for Sister | Same Day | RedHeart', description: 'Send birthday gifts to your sister — flowers, cakes & plants. Same-day & midnight delivery. Make sis feel special with RedHeart!' },
  'birthday/gifts-for-kids':    { title: 'Birthday Gifts for Kids | Fun Gifts | RedHeart', description: 'Order birthday gifts for kids — fun cakes, colourful flowers & easy plants. Same-day delivery from ₹399. Make their birthday magical with RedHeart!' },
  'birthday/roses':             { title: 'Birthday Roses | Same Day Delivery | RedHeart', description: 'Send birthday roses — fresh red, pink & mixed rose bouquets. Same-day & midnight delivery from ₹399. A classic birthday surprise from RedHeart!' },
  'birthday/chocolate-cakes':   { title: 'Birthday Chocolate Cakes Online | RedHeart', description: 'Order rich birthday chocolate cakes — truffle, ganache & fudge cakes. Same-day & midnight delivery from ₹549. Eggless available. Order at RedHeart!' },
  'birthday/surprise-gifts':    { title: 'Birthday Surprise Gifts | Same Day | RedHeart', description: 'Plan the perfect birthday surprise — flowers, cakes & plants with midnight delivery. Surprise your loved ones with RedHeart from ₹399!' },

  // ── ANNIVERSARY ────────────────────────────────────────────────────────────
  'anniversary': {
    title:       'Anniversary Gifts | Same Day Delivery | RedHeart',
    description: 'Order anniversary gifts online — romantic flowers, custom cakes & plants. Same-day & midnight delivery across India from ₹399. Celebrate love with RedHeart!',
  },
  'anniversary-gifts-delivery': {
    title:       'Anniversary Gifts | Same Day Delivery | RedHeart',
    description: 'Order anniversary gifts online — romantic flowers, custom cakes & plants. Same-day & midnight delivery across India from ₹399. Celebrate love with RedHeart!',
  },
  'anniversary/flowers':             { title: 'Anniversary Flowers | Romantic Bouquets | RedHeart', description: 'Celebrate your anniversary with stunning fresh flowers — roses, lilies & premium bouquets. Same-day & midnight delivery from ₹399. Order at RedHeart!' },
  'anniversary/cakes':               { title: 'Anniversary Cakes Online | Order Now | RedHeart', description: 'Order beautiful anniversary cakes — custom, designer & photo cakes. Same-day & midnight delivery from ₹549. Celebrate love with RedHeart!' },
  'anniversary/plants':              { title: 'Anniversary Plants Online | Green Gifts | RedHeart', description: 'Gift a plant on your anniversary — a living symbol of love. Same-day delivery from ₹299. A lasting anniversary gift. Order at RedHeart!' },
  'anniversary/gifts-for-wife':      { title: 'Anniversary Gifts for Wife | RedHeart', description: 'Surprise your wife with anniversary gifts — roses, cakes & plants with midnight delivery. Celebrate her with love from RedHeart!' },
  'anniversary/gifts-for-husband':   { title: 'Anniversary Gifts for Husband | RedHeart', description: 'Order anniversary gifts for husband — romantic flowers, cakes & plants. Same-day & midnight delivery. Celebrate him with RedHeart!' },
  'anniversary/gifts-for-parents':   { title: 'Anniversary Gifts for Parents | RedHeart', description: 'Celebrate your parents\' anniversary — flowers, cakes & plants with same-day delivery. Honour their love with a beautiful gift from RedHeart!' },
  'anniversary/gifts-for-her':       { title: 'Anniversary Gifts for Her | RedHeart', description: 'Order anniversary gifts for her — romantic flowers, cakes & plants with midnight delivery from ₹399. Make her anniversary unforgettable with RedHeart!' },
  'anniversary/gifts-for-him':       { title: 'Anniversary Gifts for Him | RedHeart', description: 'Order anniversary gifts for him — flowers, cakes & plants with same-day delivery from ₹399. Celebrate his love with RedHeart!' },
  'anniversary/gifts-for-girlfriend':{ title: 'Anniversary Gifts for Girlfriend | RedHeart', description: 'Surprise your girlfriend on your anniversary — roses, romantic cakes & plants. Midnight delivery. Make it special with RedHeart!' },
  'anniversary/gifts-for-boyfriend': { title: 'Anniversary Gifts for Boyfriend | RedHeart', description: 'Order anniversary gifts for boyfriend — flowers, cakes & plants. Same-day & midnight delivery. Celebrate your love with RedHeart!' },
  'anniversary/gifts-for-friends':   { title: 'Anniversary Gifts for Friends | RedHeart', description: 'Celebrate your friends\' anniversary — flowers, cakes & plants with same-day delivery. A thoughtful anniversary gift from RedHeart!' },
  'anniversary/roses':               { title: 'Anniversary Roses | Romantic Bouquets | RedHeart', description: 'Send anniversary roses — fresh red & pink rose bouquets. Same-day & midnight delivery from ₹399. Classic romance delivered by RedHeart!' },
  'anniversary/red-velvet':          { title: 'Anniversary Red Velvet Cake Online | RedHeart', description: 'Order a romantic red velvet anniversary cake. Same-day & midnight delivery from ₹599. A sweet celebration of love from RedHeart!' },
  'anniversary/surprise-gifts':      { title: 'Anniversary Surprise Gifts | RedHeart', description: 'Plan a perfect anniversary surprise — flowers, cakes & plants with midnight delivery. Make it unforgettable with RedHeart from ₹399!' },

  // ── WEDDING ────────────────────────────────────────────────────────────────
  'wedding': {
    title:       'Wedding Gifts Online | Flowers, Cakes & Plants | RedHeart',
    description: 'Order wedding gifts online — bridal flowers, wedding cakes & decorative plants. Same-day delivery for your special day. Premium wedding gifting at RedHeart!',
  },
  'wedding-gifts-online': {
    title:       'Wedding Gifts Online | Flowers, Cakes & Plants | RedHeart',
    description: 'Order wedding gifts online — bridal flowers, wedding cakes & decorative plants. Same-day delivery for your special day. Premium wedding gifting at RedHeart!',
  },
  'wedding/flowers':            { title: 'Wedding Flowers Online | Bridal Bouquets | RedHeart', description: 'Order stunning wedding flowers — bridal bouquets, roses & lilies for your big day. Same-day delivery. Premium wedding floral arrangements at RedHeart!' },
  'wedding/plants':             { title: 'Wedding Plants Online | Decor Plants | RedHeart', description: 'Beautiful wedding plants — bonsai, peace lily & decorative plants for wedding decor & gifting. Same-day delivery. Order wedding plants at RedHeart!' },
  'wedding/cakes':              { title: 'Wedding Cakes Online | Custom Designs | RedHeart', description: 'Order a stunning wedding cake — multi-tier, fondant & custom designs. Pre-order your dream wedding cake at RedHeart. Delivery across India!' },
  'wedding/roses':              { title: 'Wedding Roses | Fresh Bridal Roses | RedHeart', description: 'Beautiful fresh roses for weddings — red, white & mixed rose bouquets & decor. Same-day delivery. Premium wedding roses from RedHeart!' },
  'wedding/lilies':             { title: 'Wedding Lilies Online | Elegant Flowers | RedHeart', description: 'Elegant white & pink lilies for your wedding — fresh wedding lily bouquets & arrangements. Same-day delivery. Order wedding lilies at RedHeart!' },
  'wedding/carnations':         { title: 'Wedding Carnations Online | RedHeart', description: 'Fresh carnations for wedding decor — colourful & elegant wedding carnations. Same-day delivery across India. Order wedding carnations at RedHeart!' },
  'wedding/roses-and-carnation':{ title: 'Wedding Roses & Carnations | RedHeart', description: 'Stunning roses & carnation wedding arrangements. Beautiful mixed floral designs for weddings with same-day delivery. Order at RedHeart!' },
  'wedding/peace-lily':         { title: 'Wedding Peace Lily Plant | RedHeart', description: 'Elegant peace lily plants for wedding decor & gifting. Symbolic, beautiful & long-lasting. Same-day delivery. Order wedding peace lily at RedHeart!' },
  'wedding/money':              { title: 'Wedding Money Plant | Lucky Plant | RedHeart', description: 'A lucky money plant for wedding gifting — symbol of prosperity & good luck. Same-day delivery from ₹299. Order wedding money plants at RedHeart!' },
  'wedding/jade':               { title: 'Wedding Jade Plant Online | RedHeart', description: 'Gift a lucky jade plant at weddings — symbol of good fortune & prosperity. Same-day delivery from ₹249. Order wedding jade plants at RedHeart!' },
  'wedding/bonsai':             { title: 'Wedding Bonsai Plant Online | RedHeart', description: 'Unique bonsai plants for wedding gifting — artistic miniature trees as premium gifts. Same-day delivery from ₹499. Order wedding bonsai at RedHeart!' },
  'wedding/snake':              { title: 'Wedding Snake Plant Online | RedHeart', description: 'Gift a snake plant at weddings — low-maintenance, air-purifying indoor plant. Same-day delivery from ₹299. A meaningful wedding gift from RedHeart!' },
  'wedding/bouquets':           { title: 'Wedding Flower Bouquets Online | RedHeart', description: 'Stunning fresh wedding flower bouquets — bridal, bridesmaid & decor bouquets. Same-day delivery. Order beautiful wedding bouquets at RedHeart!' },
  'wedding/for-her':            { title: 'Wedding Gifts for Her | RedHeart', description: 'Order wedding gifts for her — flowers, cakes & plants. Same-day delivery. A thoughtful wedding gift for the bride or female guests from RedHeart!' },
  'wedding/for-him':            { title: 'Wedding Gifts for Him | RedHeart', description: 'Order wedding gifts for him — flowers, cakes & plants. Same-day delivery. A thoughtful wedding gift for the groom or male guests from RedHeart!' },
  'wedding/for-wife':           { title: 'Wedding Gifts for Wife | Bridal Gifts | RedHeart', description: 'Celebrate your wife with special wedding gifts — roses, cakes & plants. Same-day & midnight delivery. A beautiful wedding gift from RedHeart!' },
  'wedding/for-husband':        { title: 'Wedding Gifts for Husband | RedHeart', description: 'Order wedding gifts for your husband — flowers, cakes & plants. Same-day delivery. A meaningful wedding gift from RedHeart!' },
  'wedding/for-mother':         { title: 'Wedding Gifts for Mother | RedHeart', description: 'Beautiful wedding gifts for mothers — flowers, cakes & plants. Same-day delivery. Honour the mothers at your wedding with RedHeart!' },
  'wedding/for-father':         { title: 'Wedding Gifts for Father | RedHeart', description: 'Order wedding gifts for fathers — flowers, cakes & plants. Same-day delivery. Celebrate dads at your wedding with RedHeart!' },
  'wedding/for-friends':        { title: 'Wedding Gifts for Friends | RedHeart', description: 'Send wedding gifts to your friends — flowers, cakes & plants. Same-day delivery. A heartfelt wedding congratulations from RedHeart!' },
  'wedding/for-girlfriend':     { title: 'Wedding Gifts for Girlfriend | RedHeart', description: 'Order special wedding gifts for her — roses, cakes & plants. Midnight delivery. Celebrate love at the wedding with RedHeart!' },
  'wedding/for-boyfriend':      { title: 'Wedding Gifts for Boyfriend | RedHeart', description: 'Order wedding gifts for him — flowers, cakes & plants. Same-day delivery. Celebrate love at the wedding with RedHeart!' },
  'wedding/surprise-gifts':     { title: 'Wedding Surprise Gifts | RedHeart', description: 'Plan a wedding surprise — flowers, cakes & plants with midnight delivery. Create unforgettable wedding moments with RedHeart!' },
};

/**
 * Get meta title and description for a given category/subcategory slug combination.
 * Falls back to generated defaults if no specific entry exists.
 *
 * @param {string} categorySlug    e.g. "florist-near-me"
 * @param {string} subcategorySlug e.g. "birthday" (optional)
 * @param {string} h1Text          fallback H1 text for auto-generation
 * @returns {{ title: string, description: string }}
 */
export function getPageMeta(categorySlug, subcategorySlug, h1Text = '') {
  const key = subcategorySlug ? `${categorySlug}/${subcategorySlug}` : categorySlug;

  if (PAGE_META_MAP[key]) return PAGE_META_MAP[key];

  // Auto-generate fallback
  const label = h1Text || key.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  return {
    title:       `${label} | Same Day Delivery | RedHeart`,
    description: `Order ${label.toLowerCase()} online with same-day delivery across India. Fresh & premium quality from ₹399. Free shipping on select orders. Shop at RedHeart!`,
  };
}
